// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FileRecord,
    FileRecordFromJSON,
    FileRecordToJSON,
} from './';

/**
 * 
 * @export
 * @interface FilesGetResponse
 */
export interface FilesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof FilesGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof FilesGetResponse
     */
    previous?: string;
    /**
     * 
     * @type {string}
     * @memberof FilesGetResponse
     */
    next?: string;
    /**
     * 
     * @type {Array<FileRecord>}
     * @memberof FilesGetResponse
     */
    results: Array<FileRecord>;
}

export function FilesGetResponseFromJSON(json: any): FilesGetResponse {
    return {
        'count': json['count'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'results': (json['results'] as Array<any>).map(FileRecordFromJSON),
    };
}

export function FilesGetResponseToJSON(value?: FilesGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(FileRecordToJSON),
    };
}


