// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FileRecord,
    FileRecordFromJSON,
    FileRecordFromJSONTyped,
    FileRecordToJSON,
} from './';

/**
 * 
 * @export
 * @interface FilesGetResponse
 */
export interface FilesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof FilesGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof FilesGetResponse
     */
    previous: string | null;
    /**
     * 
     * @type {string}
     * @memberof FilesGetResponse
     */
    next: string | null;
    /**
     * 
     * @type {Array<FileRecord>}
     * @memberof FilesGetResponse
     */
    results: Array<FileRecord>;
}

export function FilesGetResponseFromJSON(json: any): FilesGetResponse {
    return FilesGetResponseFromJSONTyped(json, false);
}

export function FilesGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilesGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'previous': json['previous'],
        'next': json['next'],
        'results': (json['results'] as Array<any>).map(FileRecordFromJSON),
    };
}

export function FilesGetResponseToJSON(value?: FilesGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(FileRecordToJSON),
    };
}


