// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FileRecord
 */
export interface FileRecord {
    /**
     * 
     * @type {string}
     * @memberof FileRecord
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof FileRecord
     */
    user: number;
    /**
     * 
     * @type {string}
     * @memberof FileRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FileRecord
     */
    mime: string;
    /**
     * 
     * @type {number}
     * @memberof FileRecord
     */
    size: number;
    /**
     * 
     * @type {Date}
     * @memberof FileRecord
     */
    createdAt: Date;
}
