// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilesPostRequestBody
 */
export interface FilesPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof FilesPostRequestBody
     */
    name: string;
    /**
     * 
     * @type {Blob}
     * @memberof FilesPostRequestBody
     */
    file: Blob;
}

export function FilesPostRequestBodyFromJSON(json: any): FilesPostRequestBody {
    return {
        'name': json['name'],
        'file': json['file'],
    };
}

export function FilesPostRequestBodyToJSON(value?: FilesPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'file': value.file,
    };
}


