// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileRecord
 */
export interface FileRecord {
    /**
     * 
     * @type {string}
     * @memberof FileRecord
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof FileRecord
     */
    user: number;
    /**
     * 
     * @type {string}
     * @memberof FileRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FileRecord
     */
    mime: string | null;
    /**
     * 
     * @type {number}
     * @memberof FileRecord
     */
    size: number;
    /**
     * 
     * @type {Date}
     * @memberof FileRecord
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FileRecord
     */
    updatedAt: Date;
}

export function FileRecordFromJSON(json: any): FileRecord {
    return {
        'id': json['id'],
        'user': json['user'],
        'name': json['name'],
        'mime': json['mime'],
        'size': json['size'],
        'createdAt': new Date(json['createdAt']),
        'updatedAt': new Date(json['updatedAt']),
    };
}

export function FileRecordToJSON(value?: FileRecord): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'user': value.user,
        'name': value.name,
        'mime': value.mime,
        'size': value.size,
        'createdAt': value.createdAt.toISOString(),
        'updatedAt': value.updatedAt.toISOString(),
    };
}


