// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilesFileIdPutRequestBody
 */
export interface FilesFileIdPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof FilesFileIdPutRequestBody
     */
    name?: string;
}

export function FilesFileIdPutRequestBodyFromJSON(json: any): FilesFileIdPutRequestBody {
    return FilesFileIdPutRequestBodyFromJSONTyped(json, false);
}

export function FilesFileIdPutRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilesFileIdPutRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function FilesFileIdPutRequestBodyToJSON(value?: FilesFileIdPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


