// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FilesPostRequestBody
 */
export interface FilesPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof FilesPostRequestBody
     */
    name: string;
    /**
     * 
     * @type {Blob}
     * @memberof FilesPostRequestBody
     */
    file: Blob;
}
