// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SelectLoginUser,
} from './';

/**
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001
     */
    next?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001
     */
    previous?: number;
    /**
     * 
     * @type {Array<SelectLoginUser>}
     * @memberof InlineResponse2001
     */
    results?: Array<SelectLoginUser>;
}
