// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Locale,
    LocaleFromJSON,
    LocaleToJSON,
    Space,
    SpaceFromJSON,
    SpaceToJSON,
} from './';

/**
 * 
 * @export
 * @interface MyUser
 */
export interface MyUser {
    /**
     * 
     * @type {number}
     * @memberof MyUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MyUser
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof MyUser
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof MyUser
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof MyUser
     */
    spaceRoleId: number;
    /**
     * 
     * @type {Locale}
     * @memberof MyUser
     */
    locale: Locale;
    /**
     * 
     * @type {string}
     * @memberof MyUser
     */
    timezone: string;
    /**
     * 
     * @type {Space}
     * @memberof MyUser
     */
    space: Space;
}

export function MyUserFromJSON(json: any): MyUser {
    return {
        'id': json['id'],
        'account': json['account'],
        'displayName': json['displayName'],
        'email': json['email'],
        'spaceRoleId': json['spaceRoleId'],
        'locale': LocaleFromJSON(json['locale']),
        'timezone': json['timezone'],
        'space': SpaceFromJSON(json['space']),
    };
}

export function MyUserToJSON(value?: MyUser): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'account': value.account,
        'displayName': value.displayName,
        'email': value.email,
        'spaceRoleId': value.spaceRoleId,
        'locale': LocaleToJSON(value.locale),
        'timezone': value.timezone,
        'space': SpaceToJSON(value.space),
    };
}


