// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Locale,
    Space,
} from './';

/**
 * @export
 * @interface MyUser
 */
export interface MyUser {
    /**
     * 
     * @type {number}
     * @memberof MyUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MyUser
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof MyUser
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof MyUser
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof MyUser
     */
    spaceRoleId: number;
    /**
     * 
     * @type {Locale}
     * @memberof MyUser
     */
    locale: Locale;
    /**
     * 
     * @type {string}
     * @memberof MyUser
     */
    timezone: string;
    /**
     * 
     * @type {Space}
     * @memberof MyUser
     */
    space: Space;
}
