// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NoteStatus
 */
export interface NoteStatus {
    /**
     * 
     * @type {number}
     * @memberof NoteStatus
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof NoteStatus
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof NoteStatus
     */
    category: number;
    /**
     * 
     * @type {string}
     * @memberof NoteStatus
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NoteStatus
     */
    color: string;
    /**
     * 
     * @type {number}
     * @memberof NoteStatus
     */
    sort: number;
}
