// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotesPostRequestBody
 */
export interface NotesPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof NotesPostRequestBody
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof NotesPostRequestBody
     */
    body?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NotesPostRequestBody
     */
    status?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotesPostRequestBody
     */
    batonUser?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotesPostRequestBody
     */
    writeUser?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof NotesPostRequestBody
     */
    chargeUsers: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof NotesPostRequestBody
     */
    parentNote?: number | null;
}

export function NotesPostRequestBodyFromJSON(json: any): NotesPostRequestBody {
    return {
        'subject': json['subject'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'batonUser': !exists(json, 'batonUser') ? undefined : json['batonUser'],
        'writeUser': !exists(json, 'writeUser') ? undefined : json['writeUser'],
        'chargeUsers': json['chargeUsers'],
        'parentNote': !exists(json, 'parentNote') ? undefined : json['parentNote'],
    };
}

export function NotesPostRequestBodyToJSON(value?: NotesPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'subject': value.subject,
        'body': value.body,
        'status': value.status,
        'batonUser': value.batonUser,
        'writeUser': value.writeUser,
        'chargeUsers': value.chargeUsers,
        'parentNote': value.parentNote,
    };
}


