// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NoteSummary,
    NoteSummaryFromJSON,
    NoteSummaryFromJSONTyped,
    NoteSummaryToJSON,
} from './';

/**
 * 
 * @export
 * @interface NotesSummariesGetResponse
 */
export interface NotesSummariesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof NotesSummariesGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof NotesSummariesGetResponse
     */
    previous: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotesSummariesGetResponse
     */
    next: string | null;
    /**
     * 
     * @type {Array<NoteSummary>}
     * @memberof NotesSummariesGetResponse
     */
    results: Array<NoteSummary>;
}

export function NotesSummariesGetResponseFromJSON(json: any): NotesSummariesGetResponse {
    return NotesSummariesGetResponseFromJSONTyped(json, false);
}

export function NotesSummariesGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesSummariesGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'previous': json['previous'],
        'next': json['next'],
        'results': (json['results'] as Array<any>).map(NoteSummaryFromJSON),
    };
}

export function NotesSummariesGetResponseToJSON(value?: NotesSummariesGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(NoteSummaryToJSON),
    };
}


