// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteComment
 */
export interface NoteComment {
    /**
     * 
     * @type {number}
     * @memberof NoteComment
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof NoteComment
     */
    note?: number;
    /**
     * 
     * @type {number}
     * @memberof NoteComment
     */
    writeUser: number | null;
    /**
     * 
     * @type {string}
     * @memberof NoteComment
     */
    body: string | null;
    /**
     * 
     * @type {Date}
     * @memberof NoteComment
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof NoteComment
     */
    updatedAt: Date;
}

export function NoteCommentFromJSON(json: any): NoteComment {
    return NoteCommentFromJSONTyped(json, false);
}

export function NoteCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteComment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'writeUser': json['writeUser'],
        'body': json['body'],
        'createdAt': new Date(json['createdAt']),
        'updatedAt': new Date(json['updatedAt']),
    };
}

export function NoteCommentToJSON(value?: NoteComment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'note': value.note,
        'writeUser': value.writeUser,
        'body': value.body,
        'createdAt': value.createdAt.toISOString(),
        'updatedAt': value.updatedAt.toISOString(),
    };
}


