// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotesNoteIdPatchRequestBody
 */
export interface NotesNoteIdPatchRequestBody {
    /**
     * 
     * @type {string}
     * @memberof NotesNoteIdPatchRequestBody
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesNoteIdPatchRequestBody
     */
    body?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPatchRequestBody
     */
    status?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPatchRequestBody
     */
    batonUser?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPatchRequestBody
     */
    writeUser?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof NotesNoteIdPatchRequestBody
     */
    chargeUsers?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPatchRequestBody
     */
    parent?: number | null;
}

export function NotesNoteIdPatchRequestBodyFromJSON(json: any): NotesNoteIdPatchRequestBody {
    return NotesNoteIdPatchRequestBodyFromJSONTyped(json, false);
}

export function NotesNoteIdPatchRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesNoteIdPatchRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'batonUser': !exists(json, 'batonUser') ? undefined : json['batonUser'],
        'writeUser': !exists(json, 'writeUser') ? undefined : json['writeUser'],
        'chargeUsers': !exists(json, 'chargeUsers') ? undefined : json['chargeUsers'],
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
    };
}

export function NotesNoteIdPatchRequestBodyToJSON(value?: NotesNoteIdPatchRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject': value.subject,
        'body': value.body,
        'status': value.status,
        'batonUser': value.batonUser,
        'writeUser': value.writeUser,
        'chargeUsers': value.chargeUsers,
        'parent': value.parent,
    };
}


