// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    project: number;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    writeUser?: number;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    body?: string;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    batonUser?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof Note
     */
    chargeUsers: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    parentNote?: number;
    /**
     * 
     * @type {Date}
     * @memberof Note
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Note
     */
    updatedAt: Date;
}

export function NoteFromJSON(json: any): Note {
    return {
        'id': json['id'],
        'project': json['project'],
        'writeUser': !exists(json, 'writeUser') ? undefined : json['writeUser'],
        'subject': json['subject'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'batonUser': !exists(json, 'batonUser') ? undefined : json['batonUser'],
        'chargeUsers': json['chargeUsers'],
        'parentNote': !exists(json, 'parentNote') ? undefined : json['parentNote'],
        'createdAt': new Date(json['createdAt']),
        'updatedAt': new Date(json['updatedAt']),
    };
}

export function NoteToJSON(value?: Note): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'project': value.project,
        'writeUser': value.writeUser,
        'subject': value.subject,
        'body': value.body,
        'status': value.status,
        'batonUser': value.batonUser,
        'chargeUsers': value.chargeUsers,
        'parentNote': value.parentNote,
        'createdAt': value.createdAt.toISOString(),
        'updatedAt': value.updatedAt.toISOString(),
    };
}


