// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Note,
    NoteFromJSON,
    NoteToJSON,
} from './';

/**
 * 
 * @export
 * @interface NotesGetResponse
 */
export interface NotesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof NotesGetResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof NotesGetResponse
     */
    next: number;
    /**
     * 
     * @type {number}
     * @memberof NotesGetResponse
     */
    previous: number;
    /**
     * 
     * @type {Array<Note>}
     * @memberof NotesGetResponse
     */
    results: Array<Note>;
}

export function NotesGetResponseFromJSON(json: any): NotesGetResponse {
    return {
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': (json['results'] as Array<any>).map(NoteFromJSON),
    };
}

export function NotesGetResponseToJSON(value?: NotesGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': (value.results as Array<any>).map(NoteToJSON),
    };
}


