// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteStatus
 */
export interface NoteStatus {
    /**
     * 
     * @type {number}
     * @memberof NoteStatus
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof NoteStatus
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof NoteStatus
     */
    category: number;
    /**
     * 
     * @type {string}
     * @memberof NoteStatus
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NoteStatus
     */
    color: string | null;
    /**
     * 
     * @type {number}
     * @memberof NoteStatus
     */
    sort: number;
}

export function NoteStatusFromJSON(json: any): NoteStatus {
    return NoteStatusFromJSONTyped(json, false);
}

export function NoteStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'category': json['category'],
        'name': json['name'],
        'color': json['color'],
        'sort': json['sort'],
    };
}

export function NoteStatusToJSON(value?: NoteStatus): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'projectId': value.projectId,
        'category': value.category,
        'name': value.name,
        'color': value.color,
        'sort': value.sort,
    };
}


