// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    project: number;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    writeUser: number;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    body: string;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    status: number;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    batonUser: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof Note
     */
    chargeUsers: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    parentNote: number;
    /**
     * 
     * @type {Date}
     * @memberof Note
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Note
     */
    updatedAt: Date;
}
