// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NotesNoteIdPutRequestBody
 */
export interface NotesNoteIdPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof NotesNoteIdPutRequestBody
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesNoteIdPutRequestBody
     */
    body?: string;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPutRequestBody
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPutRequestBody
     */
    batonUser?: number;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPutRequestBody
     */
    writeUser?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof NotesNoteIdPutRequestBody
     */
    chargeUsers?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPutRequestBody
     */
    parentNote?: number;
}
