// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotesNoteIdPutRequestBody
 */
export interface NotesNoteIdPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof NotesNoteIdPutRequestBody
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesNoteIdPutRequestBody
     */
    body?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPutRequestBody
     */
    status?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPutRequestBody
     */
    batonUser?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPutRequestBody
     */
    writeUser?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof NotesNoteIdPutRequestBody
     */
    chargeUsers?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof NotesNoteIdPutRequestBody
     */
    parentNote?: number | null;
}

export function NotesNoteIdPutRequestBodyFromJSON(json: any): NotesNoteIdPutRequestBody {
    return {
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'batonUser': !exists(json, 'batonUser') ? undefined : json['batonUser'],
        'writeUser': !exists(json, 'writeUser') ? undefined : json['writeUser'],
        'chargeUsers': !exists(json, 'chargeUsers') ? undefined : json['chargeUsers'],
        'parentNote': !exists(json, 'parentNote') ? undefined : json['parentNote'],
    };
}

export function NotesNoteIdPutRequestBodyToJSON(value?: NotesNoteIdPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'subject': value.subject,
        'body': value.body,
        'status': value.status,
        'batonUser': value.batonUser,
        'writeUser': value.writeUser,
        'chargeUsers': value.chargeUsers,
        'parentNote': value.parentNote,
    };
}


