// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsProjectIdPutRequestBody
 */
export interface ProjectsProjectIdPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectIdPutRequestBody
     */
    displayName?: string;
}

export function ProjectsProjectIdPutRequestBodyFromJSON(json: any): ProjectsProjectIdPutRequestBody {
    return {
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
    };
}

export function ProjectsProjectIdPutRequestBodyToJSON(value?: ProjectsProjectIdPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'displayName': value.displayName,
    };
}


