// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProjectUser,
    ProjectUserFromJSON,
    ProjectUserFromJSONTyped,
    ProjectUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProjectsProjectIdUsersGetResponse
 */
export interface ProjectsProjectIdUsersGetResponse {
    /**
     * 
     * @type {number}
     * @memberof ProjectsProjectIdUsersGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectIdUsersGetResponse
     */
    previous: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectIdUsersGetResponse
     */
    next: string | null;
    /**
     * 
     * @type {Array<ProjectUser>}
     * @memberof ProjectsProjectIdUsersGetResponse
     */
    results: Array<ProjectUser>;
}

export function ProjectsProjectIdUsersGetResponseFromJSON(json: any): ProjectsProjectIdUsersGetResponse {
    return ProjectsProjectIdUsersGetResponseFromJSONTyped(json, false);
}

export function ProjectsProjectIdUsersGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsProjectIdUsersGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'previous': json['previous'],
        'next': json['next'],
        'results': (json['results'] as Array<any>).map(ProjectUserFromJSON),
    };
}

export function ProjectsProjectIdUsersGetResponseToJSON(value?: ProjectsProjectIdUsersGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(ProjectUserToJSON),
    };
}


