// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsPostRequestBody
 */
export interface ProjectsPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof ProjectsPostRequestBody
     */
    displayName: string;
}

export function ProjectsPostRequestBodyFromJSON(json: any): ProjectsPostRequestBody {
    return ProjectsPostRequestBodyFromJSONTyped(json, false);
}

export function ProjectsPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': json['displayName'],
    };
}

export function ProjectsPostRequestBodyToJSON(value?: ProjectsPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'displayName': value.displayName,
    };
}


