// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectUser
 */
export interface ProjectUser {
    /**
     * 
     * @type {number}
     * @memberof ProjectUser
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectUser
     */
    spaceRoleId: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectUser
     */
    projectRoleId: number | null;
}

export function ProjectUserFromJSON(json: any): ProjectUser {
    return {
        'userId': json['userId'],
        'spaceRoleId': json['spaceRoleId'],
        'projectRoleId': json['projectRoleId'],
    };
}

export function ProjectUserToJSON(value?: ProjectUser): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'userId': value.userId,
        'spaceRoleId': value.spaceRoleId,
        'projectRoleId': value.projectRoleId,
    };
}


