// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsProjectIdUsersPostRequestBody
 */
export interface ProjectsProjectIdUsersPostRequestBody {
    /**
     * 
     * @type {number}
     * @memberof ProjectsProjectIdUsersPostRequestBody
     */
    projectRoleId: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectsProjectIdUsersPostRequestBody
     */
    userId: number;
}

export function ProjectsProjectIdUsersPostRequestBodyFromJSON(json: any): ProjectsProjectIdUsersPostRequestBody {
    return {
        'projectRoleId': json['projectRoleId'],
        'userId': json['userId'],
    };
}

export function ProjectsProjectIdUsersPostRequestBodyToJSON(value?: ProjectsProjectIdUsersPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'projectRoleId': value.projectRoleId,
        'userId': value.userId,
    };
}


