// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsProjectIdUsersUserIdPutRequestBody
 */
export interface ProjectsProjectIdUsersUserIdPutRequestBody {
    /**
     * 
     * @type {number}
     * @memberof ProjectsProjectIdUsersUserIdPutRequestBody
     */
    projectRoleId?: number;
}

export function ProjectsProjectIdUsersUserIdPutRequestBodyFromJSON(json: any): ProjectsProjectIdUsersUserIdPutRequestBody {
    return ProjectsProjectIdUsersUserIdPutRequestBodyFromJSONTyped(json, false);
}

export function ProjectsProjectIdUsersUserIdPutRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsProjectIdUsersUserIdPutRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectRoleId': !exists(json, 'projectRoleId') ? undefined : json['projectRoleId'],
    };
}

export function ProjectsProjectIdUsersUserIdPutRequestBodyToJSON(value?: ProjectsProjectIdUsersUserIdPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'projectRoleId': value.projectRoleId,
    };
}


