// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProjectsProjectIdUsersPostRequestBody
 */
export interface ProjectsProjectIdUsersPostRequestBody {
    /**
     * 
     * @type {number}
     * @memberof ProjectsProjectIdUsersPostRequestBody
     */
    projectRoleId: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectsProjectIdUsersPostRequestBody
     */
    userId: number;
}
