// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Project,
} from './';

/**
 * @export
 * @interface ProjectsGetResponse
 */
export interface ProjectsGetResponse {
    /**
     * 
     * @type {number}
     * @memberof ProjectsGetResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectsGetResponse
     */
    next: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectsGetResponse
     */
    previous: number;
    /**
     * 
     * @type {Array<Project>}
     * @memberof ProjectsGetResponse
     */
    results: Array<Project>;
}
