// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecentDataValue
 */
export interface RecentDataValue {
}

export function RecentDataValueFromJSON(json: any): RecentDataValue {
    return RecentDataValueFromJSONTyped(json, false);
}

export function RecentDataValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecentDataValue {
    return json;
}

export function RecentDataValueToJSON(value?: RecentDataValue | null): any {
    return value;
}


