// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RecentDataValue,
    RecentDataValueFromJSON,
    RecentDataValueFromJSONTyped,
    RecentDataValueToJSON,
} from './';

/**
 * 
 * @export
 * @interface RecentData
 */
export interface RecentData {
    /**
     * 
     * @type {string}
     * @memberof RecentData
     */
    field: string;
    /**
     * 
     * @type {string}
     * @memberof RecentData
     */
    fieldType: string;
    /**
     * 
     * @type {RecentDataValue}
     * @memberof RecentData
     */
    beforeValue: RecentDataValue | null;
    /**
     * 
     * @type {RecentDataValue}
     * @memberof RecentData
     */
    afterValue: RecentDataValue | null;
}

export function RecentDataFromJSON(json: any): RecentData {
    return RecentDataFromJSONTyped(json, false);
}

export function RecentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecentData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': json['field'],
        'fieldType': json['fieldType'],
        'beforeValue': RecentDataValueFromJSON(json['beforeValue']),
        'afterValue': RecentDataValueFromJSON(json['afterValue']),
    };
}

export function RecentDataToJSON(value?: RecentData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
        'fieldType': value.fieldType,
        'beforeValue': RecentDataValueToJSON(value.beforeValue),
        'afterValue': RecentDataValueToJSON(value.afterValue),
    };
}


