// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RecentData,
    RecentDataFromJSON,
    RecentDataFromJSONTyped,
    RecentDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface Recent
 */
export interface Recent {
    /**
     * 
     * @type {number}
     * @memberof Recent
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Recent
     */
    space: number;
    /**
     * 
     * @type {number}
     * @memberof Recent
     */
    project: number;
    /**
     * 
     * @type {number}
     * @memberof Recent
     */
    user: number;
    /**
     * 
     * @type {string}
     * @memberof Recent
     */
    table: string;
    /**
     * 
     * @type {string}
     * @memberof Recent
     */
    event: string;
    /**
     * 
     * @type {number}
     * @memberof Recent
     */
    pk: number;
    /**
     * 
     * @type {Array<RecentData>}
     * @memberof Recent
     */
    data: Array<RecentData>;
}

export function RecentFromJSON(json: any): Recent {
    return RecentFromJSONTyped(json, false);
}

export function RecentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'space': json['space'],
        'project': json['project'],
        'user': json['user'],
        'table': json['table'],
        'event': json['event'],
        'pk': json['pk'],
        'data': (json['data'] as Array<any>).map(RecentDataFromJSON),
    };
}

export function RecentToJSON(value?: Recent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'space': value.space,
        'project': value.project,
        'user': value.user,
        'table': value.table,
        'event': value.event,
        'pk': value.pk,
        'data': (value.data as Array<any>).map(RecentDataToJSON),
    };
}


