// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Space,
    SpaceFromJSON,
    SpaceFromJSONTyped,
    SpaceToJSON,
} from './';

/**
 * 
 * @export
 * @interface SelectLoginUser
 */
export interface SelectLoginUser {
    /**
     * 
     * @type {number}
     * @memberof SelectLoginUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SelectLoginUser
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLoginUser
     */
    displayName: string | null;
    /**
     * 
     * @type {string}
     * @memberof SelectLoginUser
     */
    loginToken: string;
    /**
     * 
     * @type {Space}
     * @memberof SelectLoginUser
     */
    space: Space;
}

export function SelectLoginUserFromJSON(json: any): SelectLoginUser {
    return SelectLoginUserFromJSONTyped(json, false);
}

export function SelectLoginUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectLoginUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'account': json['account'],
        'displayName': json['displayName'],
        'loginToken': json['loginToken'],
        'space': SpaceFromJSON(json['space']),
    };
}

export function SelectLoginUserToJSON(value?: SelectLoginUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'account': value.account,
        'displayName': value.displayName,
        'loginToken': value.loginToken,
        'space': SpaceToJSON(value.space),
    };
}


