// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Space,
} from './';

/**
 * @export
 * @interface SelectLoginUser
 */
export interface SelectLoginUser {
    /**
     * 
     * @type {number}
     * @memberof SelectLoginUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SelectLoginUser
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLoginUser
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLoginUser
     */
    loginToken: string;
    /**
     * 
     * @type {Space}
     * @memberof SelectLoginUser
     */
    space: Space;
}
