// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Space,
    SpaceFromJSON,
    SpaceToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpacesGetResponse
 */
export interface SpacesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SpacesGetResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesGetResponse
     */
    next?: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesGetResponse
     */
    previous?: number;
    /**
     * 
     * @type {Array<Space>}
     * @memberof SpacesGetResponse
     */
    results: Array<Space>;
}

export function SpacesGetResponseFromJSON(json: any): SpacesGetResponse {
    return {
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': (json['results'] as Array<any>).map(SpaceFromJSON),
    };
}

export function SpacesGetResponseToJSON(value?: SpacesGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': (value.results as Array<any>).map(SpaceToJSON),
    };
}


