// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Space
 */
export interface Space {
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    displayName: string;
}

export function SpaceFromJSON(json: any): Space {
    return {
        'id': json['id'],
        'account': json['account'],
        'displayName': json['displayName'],
    };
}

export function SpaceToJSON(value?: Space): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'account': value.account,
        'displayName': value.displayName,
    };
}


