// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Space,
} from './';

/**
 * @export
 * @interface SpacesPostResponse
 */
export interface SpacesPostResponse {
    /**
     * 
     * @type {Space}
     * @memberof SpacesPostResponse
     */
    space: Space;
    /**
     * 
     * @type {string}
     * @memberof SpacesPostResponse
     */
    token: string;
}
