// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpacesSpaceIdUsersUserIdPutRequestBody
 */
export interface SpacesSpaceIdUsersUserIdPutRequestBody {
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersUserIdPutRequestBody
     */
    spaceRoleId?: number;
}

export function SpacesSpaceIdUsersUserIdPutRequestBodyFromJSON(json: any): SpacesSpaceIdUsersUserIdPutRequestBody {
    return SpacesSpaceIdUsersUserIdPutRequestBodyFromJSONTyped(json, false);
}

export function SpacesSpaceIdUsersUserIdPutRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacesSpaceIdUsersUserIdPutRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spaceRoleId': !exists(json, 'spaceRoleId') ? undefined : json['spaceRoleId'],
    };
}

export function SpacesSpaceIdUsersUserIdPutRequestBodyToJSON(value?: SpacesSpaceIdUsersUserIdPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spaceRoleId': value.spaceRoleId,
    };
}


