// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SelectLoginUser,
    SelectLoginUserFromJSON,
    SelectLoginUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpacesSpaceIdUsersGetResponse
 */
export interface SpacesSpaceIdUsersGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    previous?: string;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    next?: string;
    /**
     * 
     * @type {Array<SelectLoginUser>}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    results: Array<SelectLoginUser>;
}

export function SpacesSpaceIdUsersGetResponseFromJSON(json: any): SpacesSpaceIdUsersGetResponse {
    return {
        'count': json['count'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'results': (json['results'] as Array<any>).map(SelectLoginUserFromJSON),
    };
}

export function SpacesSpaceIdUsersGetResponseToJSON(value?: SpacesSpaceIdUsersGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(SelectLoginUserToJSON),
    };
}


