// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Recent,
    RecentFromJSON,
    RecentFromJSONTyped,
    RecentToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpacesSpaceIdRecentsGetResponse
 */
export interface SpacesSpaceIdRecentsGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdRecentsGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdRecentsGetResponse
     */
    previous: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdRecentsGetResponse
     */
    next: string | null;
    /**
     * 
     * @type {Array<Recent>}
     * @memberof SpacesSpaceIdRecentsGetResponse
     */
    results: Array<Recent>;
}

export function SpacesSpaceIdRecentsGetResponseFromJSON(json: any): SpacesSpaceIdRecentsGetResponse {
    return SpacesSpaceIdRecentsGetResponseFromJSONTyped(json, false);
}

export function SpacesSpaceIdRecentsGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacesSpaceIdRecentsGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'previous': json['previous'],
        'next': json['next'],
        'results': (json['results'] as Array<any>).map(RecentFromJSON),
    };
}

export function SpacesSpaceIdRecentsGetResponseToJSON(value?: SpacesSpaceIdRecentsGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(RecentToJSON),
    };
}


