// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SpacesPostRequestBodyOwner,
} from './';

/**
 * @export
 * @interface SpacesPostRequestBody
 */
export interface SpacesPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBody
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBody
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBody
     */
    displayName?: string;
    /**
     * 
     * @type {SpacesPostRequestBodyOwner}
     * @memberof SpacesPostRequestBody
     */
    owner: SpacesPostRequestBodyOwner;
}
