// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpacesPostRequestBodyOwner,
    SpacesPostRequestBodyOwnerFromJSON,
    SpacesPostRequestBodyOwnerToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpacesPostRequestBody
 */
export interface SpacesPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBody
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBody
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBody
     */
    displayName?: string;
    /**
     * 
     * @type {SpacesPostRequestBodyOwner}
     * @memberof SpacesPostRequestBody
     */
    owner: SpacesPostRequestBodyOwner;
}

export function SpacesPostRequestBodyFromJSON(json: any): SpacesPostRequestBody {
    return {
        'token': json['token'],
        'account': json['account'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'owner': SpacesPostRequestBodyOwnerFromJSON(json['owner']),
    };
}

export function SpacesPostRequestBodyToJSON(value?: SpacesPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'token': value.token,
        'account': value.account,
        'displayName': value.displayName,
        'owner': SpacesPostRequestBodyOwnerToJSON(value.owner),
    };
}


