// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SelectLoginUser,
} from './';

/**
 * @export
 * @interface SpacesSpaceIdUsersGetResponse
 */
export interface SpacesSpaceIdUsersGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    next: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    previous: number;
    /**
     * 
     * @type {Array<SelectLoginUser>}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    results: Array<SelectLoginUser>;
}
