// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpacesSpaceIdPutRequestBody
 */
export interface SpacesSpaceIdPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdPutRequestBody
     */
    displayName?: string | null;
}

export function SpacesSpaceIdPutRequestBodyFromJSON(json: any): SpacesSpaceIdPutRequestBody {
    return SpacesSpaceIdPutRequestBodyFromJSONTyped(json, false);
}

export function SpacesSpaceIdPutRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacesSpaceIdPutRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
    };
}

export function SpacesSpaceIdPutRequestBodyToJSON(value?: SpacesSpaceIdPutRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'displayName': value.displayName,
    };
}


