// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Space,
} from './';

/**
 * @export
 * @interface SpacesGetResponse
 */
export interface SpacesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SpacesGetResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesGetResponse
     */
    next: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesGetResponse
     */
    previous: number;
    /**
     * 
     * @type {Array<Space>}
     * @memberof SpacesGetResponse
     */
    results: Array<Space>;
}
