// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Space
 */
export interface Space {
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    displayName: string | null;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    avatarUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    avatarSmallUrl: string | null;
}

export function SpaceFromJSON(json: any): Space {
    return SpaceFromJSONTyped(json, false);
}

export function SpaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Space {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'account': json['account'],
        'displayName': json['displayName'],
        'avatarUrl': json['avatarUrl'],
        'avatarSmallUrl': json['avatarSmallUrl'],
    };
}

export function SpaceToJSON(value?: Space | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'account': value.account,
        'displayName': value.displayName,
        'avatarUrl': value.avatarUrl,
        'avatarSmallUrl': value.avatarSmallUrl,
    };
}


