// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpacesSpaceIdNoticesGetResponseResults
 */
export interface SpacesSpaceIdNoticesGetResponseResults {
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdNoticesGetResponseResults
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdNoticesGetResponseResults
     */
    user: number;
    /**
     * 
     * @type {Date}
     * @memberof SpacesSpaceIdNoticesGetResponseResults
     */
    checkedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdNoticesGetResponseResults
     */
    recent: number;
}

export function SpacesSpaceIdNoticesGetResponseResultsFromJSON(json: any): SpacesSpaceIdNoticesGetResponseResults {
    return SpacesSpaceIdNoticesGetResponseResultsFromJSONTyped(json, false);
}

export function SpacesSpaceIdNoticesGetResponseResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacesSpaceIdNoticesGetResponseResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': json['user'],
        'checkedAt': new Date(json['checkedAt']),
        'recent': json['recent'],
    };
}

export function SpacesSpaceIdNoticesGetResponseResultsToJSON(value?: SpacesSpaceIdNoticesGetResponseResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user': value.user,
        'checkedAt': value.checkedAt.toISOString(),
        'recent': value.recent,
    };
}


