// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpaceUser,
    SpaceUserFromJSON,
    SpaceUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpacesSpaceIdUsersGetResponse
 */
export interface SpacesSpaceIdUsersGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    previous: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    next: string | null;
    /**
     * 
     * @type {Array<SpaceUser>}
     * @memberof SpacesSpaceIdUsersGetResponse
     */
    results: Array<SpaceUser>;
}

export function SpacesSpaceIdUsersGetResponseFromJSON(json: any): SpacesSpaceIdUsersGetResponse {
    return {
        'count': json['count'],
        'previous': json['previous'],
        'next': json['next'],
        'results': (json['results'] as Array<any>).map(SpaceUserFromJSON),
    };
}

export function SpacesSpaceIdUsersGetResponseToJSON(value?: SpacesSpaceIdUsersGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(SpaceUserToJSON),
    };
}


