// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpacesSpaceIdUsersUserIdAvatarPostRequestBody
 */
export interface SpacesSpaceIdUsersUserIdAvatarPostRequestBody {
    /**
     * 
     * @type {Blob}
     * @memberof SpacesSpaceIdUsersUserIdAvatarPostRequestBody
     */
    avatar: Blob;
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersUserIdAvatarPostRequestBody
     */
    left: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersUserIdAvatarPostRequestBody
     */
    top: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersUserIdAvatarPostRequestBody
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdUsersUserIdAvatarPostRequestBody
     */
    height: number;
}

export function SpacesSpaceIdUsersUserIdAvatarPostRequestBodyFromJSON(json: any): SpacesSpaceIdUsersUserIdAvatarPostRequestBody {
    return SpacesSpaceIdUsersUserIdAvatarPostRequestBodyFromJSONTyped(json, false);
}

export function SpacesSpaceIdUsersUserIdAvatarPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacesSpaceIdUsersUserIdAvatarPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatar': json['avatar'],
        'left': json['left'],
        'top': json['top'],
        'width': json['width'],
        'height': json['height'],
    };
}

export function SpacesSpaceIdUsersUserIdAvatarPostRequestBodyToJSON(value?: SpacesSpaceIdUsersUserIdAvatarPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatar': value.avatar,
        'left': value.left,
        'top': value.top,
        'width': value.width,
        'height': value.height,
    };
}


