// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpaceUser
 */
export interface SpaceUser {
    /**
     * 
     * @type {number}
     * @memberof SpaceUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SpaceUser
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceUser
     */
    displayName: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpaceUser
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof SpaceUser
     */
    spaceId: number;
    /**
     * 
     * @type {number}
     * @memberof SpaceUser
     */
    spaceRoleId: number;
}

export function SpaceUserFromJSON(json: any): SpaceUser {
    return {
        'id': json['id'],
        'account': json['account'],
        'displayName': json['displayName'],
        'email': json['email'],
        'spaceId': json['spaceId'],
        'spaceRoleId': json['spaceRoleId'],
    };
}

export function SpaceUserToJSON(value?: SpaceUser): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'account': value.account,
        'displayName': value.displayName,
        'email': value.email,
        'spaceId': value.spaceId,
        'spaceRoleId': value.spaceRoleId,
    };
}


