// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SpaceUser
 */
export interface SpaceUser {
    /**
     * 
     * @type {number}
     * @memberof SpaceUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SpaceUser
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceUser
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceUser
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof SpaceUser
     */
    spaceId: number;
    /**
     * 
     * @type {number}
     * @memberof SpaceUser
     */
    spaceRoleId: number;
}
