// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpacesSpaceIdNoticesGetResponseResults,
    SpacesSpaceIdNoticesGetResponseResultsFromJSON,
    SpacesSpaceIdNoticesGetResponseResultsFromJSONTyped,
    SpacesSpaceIdNoticesGetResponseResultsToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpacesSpaceIdNoticesGetResponse
 */
export interface SpacesSpaceIdNoticesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SpacesSpaceIdNoticesGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdNoticesGetResponse
     */
    previous: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdNoticesGetResponse
     */
    next: string | null;
    /**
     * 
     * @type {Array<SpacesSpaceIdNoticesGetResponseResults>}
     * @memberof SpacesSpaceIdNoticesGetResponse
     */
    results: Array<SpacesSpaceIdNoticesGetResponseResults>;
}

export function SpacesSpaceIdNoticesGetResponseFromJSON(json: any): SpacesSpaceIdNoticesGetResponse {
    return SpacesSpaceIdNoticesGetResponseFromJSONTyped(json, false);
}

export function SpacesSpaceIdNoticesGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacesSpaceIdNoticesGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'previous': json['previous'],
        'next': json['next'],
        'results': (json['results'] as Array<any>).map(SpacesSpaceIdNoticesGetResponseResultsFromJSON),
    };
}

export function SpacesSpaceIdNoticesGetResponseToJSON(value?: SpacesSpaceIdNoticesGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(SpacesSpaceIdNoticesGetResponseResultsToJSON),
    };
}


