// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Space,
    SpaceFromJSON,
    SpaceFromJSONTyped,
    SpaceToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpacesGetResponse
 */
export interface SpacesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SpacesGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof SpacesGetResponse
     */
    previous: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpacesGetResponse
     */
    next: string | null;
    /**
     * 
     * @type {Array<Space>}
     * @memberof SpacesGetResponse
     */
    results: Array<Space>;
}

export function SpacesGetResponseFromJSON(json: any): SpacesGetResponse {
    return SpacesGetResponseFromJSONTyped(json, false);
}

export function SpacesGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacesGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'previous': json['previous'],
        'next': json['next'],
        'results': (json['results'] as Array<any>).map(SpaceFromJSON),
    };
}

export function SpacesGetResponseToJSON(value?: SpacesGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(SpaceToJSON),
    };
}


