// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpacesSpaceIdAvatarPostResponse
 */
export interface SpacesSpaceIdAvatarPostResponse {
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdAvatarPostResponse
     */
    avatarUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpacesSpaceIdAvatarPostResponse
     */
    avatarSmallUrl: string | null;
}

export function SpacesSpaceIdAvatarPostResponseFromJSON(json: any): SpacesSpaceIdAvatarPostResponse {
    return SpacesSpaceIdAvatarPostResponseFromJSONTyped(json, false);
}

export function SpacesSpaceIdAvatarPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacesSpaceIdAvatarPostResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatarUrl'],
        'avatarSmallUrl': json['avatarSmallUrl'],
    };
}

export function SpacesSpaceIdAvatarPostResponseToJSON(value?: SpacesSpaceIdAvatarPostResponse): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatarUrl': value.avatarUrl,
        'avatarSmallUrl': value.avatarSmallUrl,
    };
}


