// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpacesPostRequestBodyOwner
 */
export interface SpacesPostRequestBodyOwner {
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBodyOwner
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBodyOwner
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof SpacesPostRequestBodyOwner
     */
    displayName?: string | null;
}

export function SpacesPostRequestBodyOwnerFromJSON(json: any): SpacesPostRequestBodyOwner {
    return {
        'email': json['email'],
        'account': json['account'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
    };
}

export function SpacesPostRequestBodyOwnerToJSON(value?: SpacesPostRequestBodyOwner): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'email': value.email,
        'account': value.account,
        'displayName': value.displayName,
    };
}


