// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskStatus
 */
export interface TaskStatus {
    /**
     * 
     * @type {number}
     * @memberof TaskStatus
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStatus
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStatus
     */
    category: number;
    /**
     * 
     * @type {string}
     * @memberof TaskStatus
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaskStatus
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskStatus
     */
    sort: number;
}

export function TaskStatusFromJSON(json: any): TaskStatus {
    return {
        'id': json['id'],
        'projectId': !exists(json, 'projectId') ? undefined : json['projectId'],
        'category': json['category'],
        'name': json['name'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'sort': json['sort'],
    };
}

export function TaskStatusToJSON(value?: TaskStatus): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'projectId': value.projectId,
        'category': value.category,
        'name': value.name,
        'color': value.color,
        'sort': value.sort,
    };
}


