// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TasksStatusPostRequestBodyItem
 */
export interface TasksStatusPostRequestBodyItem {
    /**
     * 
     * @type {number}
     * @memberof TasksStatusPostRequestBodyItem
     */
    category: number;
    /**
     * 
     * @type {string}
     * @memberof TasksStatusPostRequestBodyItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TasksStatusPostRequestBodyItem
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TasksStatusPostRequestBodyItem
     */
    sort: number;
}

export function TasksStatusPostRequestBodyItemFromJSON(json: any): TasksStatusPostRequestBodyItem {
    return {
        'category': json['category'],
        'name': json['name'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'sort': json['sort'],
    };
}

export function TasksStatusPostRequestBodyItemToJSON(value?: TasksStatusPostRequestBodyItem): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'category': value.category,
        'name': value.name,
        'color': value.color,
        'sort': value.sort,
    };
}


