// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskCommmentsPostRequestBody
 */
export interface TaskCommmentsPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof TaskCommmentsPostRequestBody
     */
    body?: string | null;
}

export function TaskCommmentsPostRequestBodyFromJSON(json: any): TaskCommmentsPostRequestBody {
    return TaskCommmentsPostRequestBodyFromJSONTyped(json, false);
}

export function TaskCommmentsPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCommmentsPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': !exists(json, 'body') ? undefined : json['body'],
    };
}

export function TaskCommmentsPostRequestBodyToJSON(value?: TaskCommmentsPostRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
    };
}


