// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TasksTaskIdFavoriteGetResponse
 */
export interface TasksTaskIdFavoriteGetResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TasksTaskIdFavoriteGetResponse
     */
    value: boolean;
}

export function TasksTaskIdFavoriteGetResponseFromJSON(json: any): TasksTaskIdFavoriteGetResponse {
    return TasksTaskIdFavoriteGetResponseFromJSONTyped(json, false);
}

export function TasksTaskIdFavoriteGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksTaskIdFavoriteGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function TasksTaskIdFavoriteGetResponseToJSON(value?: TasksTaskIdFavoriteGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}


