// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TaskStatus
 */
export interface TaskStatus {
    /**
     * 
     * @type {number}
     * @memberof TaskStatus
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStatus
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStatus
     */
    category: number;
    /**
     * 
     * @type {string}
     * @memberof TaskStatus
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TaskStatus
     */
    sort: number;
}
