// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SpacesSpaceIdProjectsProjectIdTasksTags,
} from './';

/**
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    project: number;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    writeUser: number;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    body: string;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    limitedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    status: number;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    batonUser: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof Task
     */
    chargeUsers: Array<number>;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    updatedAt: Date;
    /**
     * 
     * @type {Array<SpacesSpaceIdProjectsProjectIdTasksTags>}
     * @memberof Task
     */
    tags: Array<SpacesSpaceIdProjectsProjectIdTasksTags>;
}
