// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TasksTaskIdPriorityPostRequestBody
 */
export interface TasksTaskIdPriorityPostRequestBody {
    /**
     * 
     * @type {number}
     * @memberof TasksTaskIdPriorityPostRequestBody
     */
    parent?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TasksTaskIdPriorityPostRequestBody
     */
    nextHighestTask?: number | null;
}

export function TasksTaskIdPriorityPostRequestBodyFromJSON(json: any): TasksTaskIdPriorityPostRequestBody {
    return TasksTaskIdPriorityPostRequestBodyFromJSONTyped(json, false);
}

export function TasksTaskIdPriorityPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksTaskIdPriorityPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'nextHighestTask': !exists(json, 'next_highest_task') ? undefined : json['next_highest_task'],
    };
}

export function TasksTaskIdPriorityPostRequestBodyToJSON(value?: TasksTaskIdPriorityPostRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent': value.parent,
        'next_highest_task': value.nextHighestTask,
    };
}


