// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TaskComment,
} from './';

/**
 * @export
 * @interface TaskCommmentsGetResponse
 */
export interface TaskCommmentsGetResponse {
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsGetResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsGetResponse
     */
    next: number;
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsGetResponse
     */
    previous: number;
    /**
     * 
     * @type {Array<TaskComment>}
     * @memberof TaskCommmentsGetResponse
     */
    results: Array<TaskComment>;
}
