// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TaskCommentFile,
} from './';

/**
 * @export
 * @interface TaskComment
 */
export interface TaskComment {
    /**
     * 
     * @type {number}
     * @memberof TaskComment
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TaskComment
     */
    task: number;
    /**
     * 
     * @type {number}
     * @memberof TaskComment
     */
    writeUser: number;
    /**
     * 
     * @type {string}
     * @memberof TaskComment
     */
    body: string;
    /**
     * 
     * @type {Array<TaskCommentFile>}
     * @memberof TaskComment
     */
    files: Array<TaskCommentFile>;
    /**
     * 
     * @type {Date}
     * @memberof TaskComment
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskComment
     */
    updatedAt: Date;
}
