// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpacesSpaceIdProjectsProjectIdTasksTags,
    SpacesSpaceIdProjectsProjectIdTasksTagsFromJSON,
    SpacesSpaceIdProjectsProjectIdTasksTagsFromJSONTyped,
    SpacesSpaceIdProjectsProjectIdTasksTagsToJSON,
} from './';

/**
 *
 * @export
 * @interface TasksTaskIdPatchRequestBody
 */
export interface TasksTaskIdPatchRequestBody {
    /**
     *
     * @type {number}
     * @memberof TasksTaskIdPatchRequestBody
     */
    parent?: number | null;
    /**
     *
     * @type {string}
     * @memberof TasksTaskIdPatchRequestBody
     */
    subject?: string;
    /**
     *
     * @type {string}
     * @memberof TasksTaskIdPatchRequestBody
     */
    body?: string | null;
    /**
     *
     * @type {Date}
     * @memberof TasksTaskIdPatchRequestBody
     */
    startedAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof TasksTaskIdPatchRequestBody
     */
    limitedAt?: Date | null;
    /**
     *
     * @type {number}
     * @memberof TasksTaskIdPatchRequestBody
     */
    status?: number | null;
    /**
     *
     * @type {number}
     * @memberof TasksTaskIdPatchRequestBody
     */
    batonUser?: number;
    /**
     *
     * @type {Array<number>}
     * @memberof TasksTaskIdPatchRequestBody
     */
    chargeUsers?: Array<number>;
    /**
     *
     * @type {Array<SpacesSpaceIdProjectsProjectIdTasksTags>}
     * @memberof TasksTaskIdPatchRequestBody
     */
    tags?: Array<SpacesSpaceIdProjectsProjectIdTasksTags>;
}

export function TasksTaskIdPatchRequestBodyFromJSON(json: any): TasksTaskIdPatchRequestBody {
    return TasksTaskIdPatchRequestBodyFromJSONTyped(json, false);
}

export function TasksTaskIdPatchRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksTaskIdPatchRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'startedAt': !exists(json, 'startedAt') ? undefined : new Date(json['startedAt']),
        'limitedAt': !exists(json, 'limitedAt') ? undefined : new Date(json['limitedAt']),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'batonUser': !exists(json, 'batonUser') ? undefined : json['batonUser'],
        'chargeUsers': !exists(json, 'chargeUsers') ? undefined : json['chargeUsers'],
        'tags': !exists(json, 'tags') ? undefined : (json['tags'] as Array<any>).map(SpacesSpaceIdProjectsProjectIdTasksTagsFromJSON),
    };
}

export function TasksTaskIdPatchRequestBodyToJSON(value?: TasksTaskIdPatchRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'parent': value.parent,
        'subject': value.subject,
        'body': value.body,
        'startedAt': !value.startedAt ? (value.startedAt === null ? null : undefined) : value.startedAt.toISOString().substr(0, 10),
        'limitedAt': !value.limitedAt ? (value.limitedAt === null ? null : undefined) : value.limitedAt.toISOString().substr(0, 10),
        'status': value.status,
        'batonUser': value.batonUser,
        'chargeUsers': value.chargeUsers,
        'tags': value.tags === undefined ? undefined : (value.tags as Array<any>).map(SpacesSpaceIdProjectsProjectIdTasksTagsToJSON),
    };
}


