// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskCommmentsTaskCommentIdPutRequestBody
 */
export interface TaskCommmentsTaskCommentIdPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof TaskCommmentsTaskCommentIdPutRequestBody
     */
    body?: string | null;
}

export function TaskCommmentsTaskCommentIdPutRequestBodyFromJSON(json: any): TaskCommmentsTaskCommentIdPutRequestBody {
    return TaskCommmentsTaskCommentIdPutRequestBodyFromJSONTyped(json, false);
}

export function TaskCommmentsTaskCommentIdPutRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCommmentsTaskCommentIdPutRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': !exists(json, 'body') ? undefined : json['body'],
    };
}

export function TaskCommmentsTaskCommentIdPutRequestBodyToJSON(value?: TaskCommmentsTaskCommentIdPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
    };
}


