// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody
 */
export interface TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody
     */
    name?: string;
}

export function TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBodyFromJSON(json: any): TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBodyToJSON(value?: TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
    };
}


