// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskCommentFile
 */
export interface TaskCommentFile {
    /**
     * 
     * @type {string}
     * @memberof TaskCommentFile
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof TaskCommentFile
     */
    comment: number;
    /**
     * 
     * @type {string}
     * @memberof TaskCommentFile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaskCommentFile
     */
    mime: string;
    /**
     * 
     * @type {number}
     * @memberof TaskCommentFile
     */
    size: number;
}

export function TaskCommentFileFromJSON(json: any): TaskCommentFile {
    return {
        'id': json['id'],
        'comment': json['comment'],
        'name': json['name'],
        'mime': json['mime'],
        'size': json['size'],
    };
}

export function TaskCommentFileToJSON(value?: TaskCommentFile): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'comment': value.comment,
        'name': value.name,
        'mime': value.mime,
        'size': value.size,
    };
}


