// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Task,
    TaskFromJSON,
    TaskToJSON,
} from './';

/**
 * 
 * @export
 * @interface TasksGetResponse
 */
export interface TasksGetResponse {
    /**
     * 
     * @type {number}
     * @memberof TasksGetResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof TasksGetResponse
     */
    previous?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksGetResponse
     */
    next?: string;
    /**
     * 
     * @type {Array<Task>}
     * @memberof TasksGetResponse
     */
    results: Array<Task>;
}

export function TasksGetResponseFromJSON(json: any): TasksGetResponse {
    return {
        'count': json['count'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'results': (json['results'] as Array<any>).map(TaskFromJSON),
    };
}

export function TasksGetResponseToJSON(value?: TasksGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
        'previous': value.previous,
        'next': value.next,
        'results': (value.results as Array<any>).map(TaskToJSON),
    };
}


