// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SpacesSpaceIdProjectsProjectIdTasksTags,
} from './';

/**
 * @export
 * @interface TasksTaskIdPutRequestBody
 */
export interface TasksTaskIdPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof TasksTaskIdPutRequestBody
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksTaskIdPutRequestBody
     */
    body?: string;
    /**
     * 
     * @type {Date}
     * @memberof TasksTaskIdPutRequestBody
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TasksTaskIdPutRequestBody
     */
    limitedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TasksTaskIdPutRequestBody
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof TasksTaskIdPutRequestBody
     */
    batonUser?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof TasksTaskIdPutRequestBody
     */
    chargeUsers?: Array<number>;
    /**
     * 
     * @type {Array<SpacesSpaceIdProjectsProjectIdTasksTags>}
     * @memberof TasksTaskIdPutRequestBody
     */
    tags?: Array<SpacesSpaceIdProjectsProjectIdTasksTags>;
}
