// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaskComment,
    TaskCommentFromJSON,
    TaskCommentToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaskCommmentsGetResponse
 */
export interface TaskCommmentsGetResponse {
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsGetResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsGetResponse
     */
    next: number;
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsGetResponse
     */
    previous: number;
    /**
     * 
     * @type {Array<TaskComment>}
     * @memberof TaskCommmentsGetResponse
     */
    results: Array<TaskComment>;
}

export function TaskCommmentsGetResponseFromJSON(json: any): TaskCommmentsGetResponse {
    return {
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': (json['results'] as Array<any>).map(TaskCommentFromJSON),
    };
}

export function TaskCommmentsGetResponseToJSON(value?: TaskCommmentsGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': (value.results as Array<any>).map(TaskCommentToJSON),
    };
}


