// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaskCommentFile,
    TaskCommentFileFromJSON,
    TaskCommentFileFromJSONTyped,
    TaskCommentFileToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaskComment
 */
export interface TaskComment {
    /**
     * 
     * @type {number}
     * @memberof TaskComment
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TaskComment
     */
    task: number;
    /**
     * 
     * @type {number}
     * @memberof TaskComment
     */
    writeUser: number | null;
    /**
     * 
     * @type {string}
     * @memberof TaskComment
     */
    body: string | null;
    /**
     * 
     * @type {Array<TaskCommentFile>}
     * @memberof TaskComment
     */
    files: Array<TaskCommentFile>;
    /**
     * 
     * @type {Date}
     * @memberof TaskComment
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskComment
     */
    updatedAt: Date;
}

export function TaskCommentFromJSON(json: any): TaskComment {
    return TaskCommentFromJSONTyped(json, false);
}

export function TaskCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskComment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'task': json['task'],
        'writeUser': json['writeUser'],
        'body': json['body'],
        'files': (json['files'] as Array<any>).map(TaskCommentFileFromJSON),
        'createdAt': new Date(json['createdAt']),
        'updatedAt': new Date(json['updatedAt']),
    };
}

export function TaskCommentToJSON(value?: TaskComment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'task': value.task,
        'writeUser': value.writeUser,
        'body': value.body,
        'files': (value.files as Array<any>).map(TaskCommentFileToJSON),
        'createdAt': value.createdAt.toISOString(),
        'updatedAt': value.updatedAt.toISOString(),
    };
}


