// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaskCommentFile,
    TaskCommentFileFromJSON,
    TaskCommentFileToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaskCommmentsTaskCommentIdFilesGetResponse
 */
export interface TaskCommmentsTaskCommentIdFilesGetResponse {
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsTaskCommentIdFilesGetResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsTaskCommentIdFilesGetResponse
     */
    next?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskCommmentsTaskCommentIdFilesGetResponse
     */
    previous?: number;
    /**
     * 
     * @type {Array<TaskCommentFile>}
     * @memberof TaskCommmentsTaskCommentIdFilesGetResponse
     */
    results: Array<TaskCommentFile>;
}

export function TaskCommmentsTaskCommentIdFilesGetResponseFromJSON(json: any): TaskCommmentsTaskCommentIdFilesGetResponse {
    return {
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': (json['results'] as Array<any>).map(TaskCommentFileFromJSON),
    };
}

export function TaskCommmentsTaskCommentIdFilesGetResponseToJSON(value?: TaskCommmentsTaskCommentIdFilesGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': (value.results as Array<any>).map(TaskCommentFileToJSON),
    };
}


