// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersSmsLoginConfirmPostRequestBody
 */
export interface UsersSmsLoginConfirmPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersSmsLoginConfirmPostRequestBody
     */
    sms: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof UsersSmsLoginConfirmPostRequestBody
     */
    idNotIn?: Array<number>;
}

export function UsersSmsLoginConfirmPostRequestBodyFromJSON(json: any): UsersSmsLoginConfirmPostRequestBody {
    return UsersSmsLoginConfirmPostRequestBodyFromJSONTyped(json, false);
}

export function UsersSmsLoginConfirmPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersSmsLoginConfirmPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sms': json['sms'],
        'idNotIn': !exists(json, 'idNotIn') ? undefined : json['idNotIn'],
    };
}

export function UsersSmsLoginConfirmPostRequestBodyToJSON(value?: UsersSmsLoginConfirmPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sms': value.sms,
        'idNotIn': value.idNotIn,
    };
}


