// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UsersLoginPostRequestBody
 */
export interface UsersLoginPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersLoginPostRequestBody
     */
    token: string;
    /**
     * 
     * @type {number}
     * @memberof UsersLoginPostRequestBody
     */
    spaceId: number;
    /**
     * 
     * @type {number}
     * @memberof UsersLoginPostRequestBody
     */
    userId: number;
}
