// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MyUser,
    MyUserFromJSON,
    MyUserFromJSONTyped,
    MyUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface UsersLoginPostResponse
 */
export interface UsersLoginPostResponse {
    /**
     * 
     * @type {string}
     * @memberof UsersLoginPostResponse
     */
    token: string;
    /**
     * 
     * @type {MyUser}
     * @memberof UsersLoginPostResponse
     */
    user: MyUser;
}

export function UsersLoginPostResponseFromJSON(json: any): UsersLoginPostResponse {
    return UsersLoginPostResponseFromJSONTyped(json, false);
}

export function UsersLoginPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersLoginPostResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'user': MyUserFromJSON(json['user']),
    };
}

export function UsersLoginPostResponseToJSON(value?: UsersLoginPostResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'user': MyUserToJSON(value.user),
    };
}


