// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersMeEmailPutRequestBody
 */
export interface UsersMeEmailPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersMeEmailPutRequestBody
     */
    token: string;
}

export function UsersMeEmailPutRequestBodyFromJSON(json: any): UsersMeEmailPutRequestBody {
    return {
        'token': json['token'],
    };
}

export function UsersMeEmailPutRequestBodyToJSON(value?: UsersMeEmailPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'token': value.token,
    };
}


