// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Locale,
} from './';

/**
 * @export
 * @interface UsersMePutRequestBody
 */
export interface UsersMePutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersMePutRequestBody
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersMePutRequestBody
     */
    displayName?: string;
    /**
     * 
     * @type {Locale}
     * @memberof UsersMePutRequestBody
     */
    locale?: Locale;
    /**
     * 
     * @type {string}
     * @memberof UsersMePutRequestBody
     */
    timezone?: string;
}
