// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersSmsLoginConfirmPostResponse
 */
export interface UsersSmsLoginConfirmPostResponse {
    /**
     * 
     * @type {string}
     * @memberof UsersSmsLoginConfirmPostResponse
     */
    token: string;
}

export function UsersSmsLoginConfirmPostResponseFromJSON(json: any): UsersSmsLoginConfirmPostResponse {
    return {
        'token': json['token'],
    };
}

export function UsersSmsLoginConfirmPostResponseToJSON(value?: UsersSmsLoginConfirmPostResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'token': value.token,
    };
}


