// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Locale,
    LocaleFromJSON,
    LocaleFromJSONTyped,
    LocaleToJSON,
} from './';

/**
 * 
 * @export
 * @interface UsersMePatchRequestBody
 */
export interface UsersMePatchRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersMePatchRequestBody
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersMePatchRequestBody
     */
    displayName?: string | null;
    /**
     * 
     * @type {Locale}
     * @memberof UsersMePatchRequestBody
     */
    locale?: Locale;
    /**
     * 
     * @type {string}
     * @memberof UsersMePatchRequestBody
     */
    timezone?: string;
}

export function UsersMePatchRequestBodyFromJSON(json: any): UsersMePatchRequestBody {
    return UsersMePatchRequestBodyFromJSONTyped(json, false);
}

export function UsersMePatchRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMePatchRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account': !exists(json, 'account') ? undefined : json['account'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'locale': !exists(json, 'locale') ? undefined : LocaleFromJSON(json['locale']),
        'timezone': !exists(json, 'timezone') ? undefined : json['timezone'],
    };
}

export function UsersMePatchRequestBodyToJSON(value?: UsersMePatchRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account': value.account,
        'displayName': value.displayName,
        'locale': LocaleToJSON(value.locale),
        'timezone': value.timezone,
    };
}


