// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersEmailLoginPostRequestBody
 */
export interface UsersEmailLoginPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersEmailLoginPostRequestBody
     */
    token: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof UsersEmailLoginPostRequestBody
     */
    idNotIn?: Array<number>;
}

export function UsersEmailLoginPostRequestBodyFromJSON(json: any): UsersEmailLoginPostRequestBody {
    return UsersEmailLoginPostRequestBodyFromJSONTyped(json, false);
}

export function UsersEmailLoginPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersEmailLoginPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'idNotIn': !exists(json, 'idNotIn') ? undefined : json['idNotIn'],
    };
}

export function UsersEmailLoginPostRequestBodyToJSON(value?: UsersEmailLoginPostRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'idNotIn': value.idNotIn,
    };
}


