// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersMeSmsPutRequestBody
 */
export interface UsersMeSmsPutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersMeSmsPutRequestBody
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof UsersMeSmsPutRequestBody
     */
    pin: string;
}

export function UsersMeSmsPutRequestBodyFromJSON(json: any): UsersMeSmsPutRequestBody {
    return UsersMeSmsPutRequestBodyFromJSONTyped(json, false);
}

export function UsersMeSmsPutRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMeSmsPutRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'pin': json['pin'],
    };
}

export function UsersMeSmsPutRequestBodyToJSON(value?: UsersMeSmsPutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'pin': value.pin,
    };
}


