// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersMeSmsGetResponse
 */
export interface UsersMeSmsGetResponse {
    /**
     * 
     * @type {string}
     * @memberof UsersMeSmsGetResponse
     */
    sms: string;
}

export function UsersMeSmsGetResponseFromJSON(json: any): UsersMeSmsGetResponse {
    return UsersMeSmsGetResponseFromJSONTyped(json, false);
}

export function UsersMeSmsGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMeSmsGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sms': json['sms'],
    };
}

export function UsersMeSmsGetResponseToJSON(value?: UsersMeSmsGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sms': value.sms,
    };
}


