// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersMeSmsConfirmPostRequestBody
 */
export interface UsersMeSmsConfirmPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersMeSmsConfirmPostRequestBody
     */
    sms: string;
}

export function UsersMeSmsConfirmPostRequestBodyFromJSON(json: any): UsersMeSmsConfirmPostRequestBody {
    return UsersMeSmsConfirmPostRequestBodyFromJSONTyped(json, false);
}

export function UsersMeSmsConfirmPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMeSmsConfirmPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sms': json['sms'],
    };
}

export function UsersMeSmsConfirmPostRequestBodyToJSON(value?: UsersMeSmsConfirmPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sms': value.sms,
    };
}


