// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersEmailLoginConfirmPostRequestBody
 */
export interface UsersEmailLoginConfirmPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersEmailLoginConfirmPostRequestBody
     */
    email: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof UsersEmailLoginConfirmPostRequestBody
     */
    idNotIn?: Array<number>;
}

export function UsersEmailLoginConfirmPostRequestBodyFromJSON(json: any): UsersEmailLoginConfirmPostRequestBody {
    return UsersEmailLoginConfirmPostRequestBodyFromJSONTyped(json, false);
}

export function UsersEmailLoginConfirmPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersEmailLoginConfirmPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'idNotIn': !exists(json, 'idNotIn') ? undefined : json['idNotIn'],
    };
}

export function UsersEmailLoginConfirmPostRequestBodyToJSON(value?: UsersEmailLoginConfirmPostRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'idNotIn': value.idNotIn,
    };
}


