// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersMeEmailGetResponse
 */
export interface UsersMeEmailGetResponse {
    /**
     * 
     * @type {string}
     * @memberof UsersMeEmailGetResponse
     */
    email: string;
}

export function UsersMeEmailGetResponseFromJSON(json: any): UsersMeEmailGetResponse {
    return {
        'email': json['email'],
    };
}

export function UsersMeEmailGetResponseToJSON(value?: UsersMeEmailGetResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'email': value.email,
    };
}


