// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersMeEmailConfirmPostRequestBody
 */
export interface UsersMeEmailConfirmPostRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersMeEmailConfirmPostRequestBody
     */
    email: string;
}

export function UsersMeEmailConfirmPostRequestBodyFromJSON(json: any): UsersMeEmailConfirmPostRequestBody {
    return UsersMeEmailConfirmPostRequestBodyFromJSONTyped(json, false);
}

export function UsersMeEmailConfirmPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMeEmailConfirmPostRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function UsersMeEmailConfirmPostRequestBodyToJSON(value?: UsersMeEmailConfirmPostRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}


