// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Locale,
    LocaleFromJSON,
    LocaleToJSON,
} from './';

/**
 * 
 * @export
 * @interface UsersMePutRequestBody
 */
export interface UsersMePutRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UsersMePutRequestBody
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersMePutRequestBody
     */
    displayName?: string;
    /**
     * 
     * @type {Locale}
     * @memberof UsersMePutRequestBody
     */
    locale?: Locale;
    /**
     * 
     * @type {string}
     * @memberof UsersMePutRequestBody
     */
    timezone?: string;
}

export function UsersMePutRequestBodyFromJSON(json: any): UsersMePutRequestBody {
    return {
        'account': !exists(json, 'account') ? undefined : json['account'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'locale': !exists(json, 'locale') ? undefined : LocaleFromJSON(json['locale']),
        'timezone': !exists(json, 'timezone') ? undefined : json['timezone'],
    };
}

export function UsersMePutRequestBodyToJSON(value?: UsersMePutRequestBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'account': value.account,
        'displayName': value.displayName,
        'locale': LocaleToJSON(value.locale),
        'timezone': value.timezone,
    };
}


