// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    FileRecord,
    FileRecordFromJSON,
    FileRecordToJSON,
    FilesFileIdPutRequestBody,
    FilesFileIdPutRequestBodyFromJSON,
    FilesFileIdPutRequestBodyToJSON,
    FilesGetResponse,
    FilesGetResponseFromJSON,
    FilesGetResponseToJSON,
} from '../models';

export interface FilesFileIdDeleteRequest {
    spaceId: number;
    projectId: number;
    fileId: number;
}

export interface FilesFileIdGetRequest {
    spaceId: number;
    projectId: number;
    fileId: number;
}

export interface FilesFileIdPutRequest {
    spaceId: number;
    projectId: number;
    fileId: number;
    filesFileIdPutRequestBody: FilesFileIdPutRequestBody;
}

export interface FilesGetRequest {
    spaceId: number;
    projectId: number;
    page?: number;
    limit?: number;
    id?: number;
    idGt?: number;
    idLt?: number;
    name?: string;
    userId?: number;
    updatedAt?: Date;
    updatedAtGt?: Date;
    updatedAtLt?: Date;
    ordering?: string;
}

export interface FilesPostRequest {
    spaceId: number;
    projectId: number;
    name: string;
    file: Blob;
}

/**
 * no description
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     */
    async filesFileIdDeleteRaw(requestParameters: FilesFileIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesFileIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesFileIdDelete.');
        }

        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new runtime.RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling filesFileIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/files/{fileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async filesFileIdDelete(requestParameters: FilesFileIdDeleteRequest): Promise<void> {
        await this.filesFileIdDeleteRaw(requestParameters);
    }

    /**
     */
    async filesFileIdGetRaw(requestParameters: FilesFileIdGetRequest): Promise<runtime.ApiResponse<FileRecord>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesFileIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesFileIdGet.');
        }

        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new runtime.RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling filesFileIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/files/{fileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => FileRecordFromJSON(jsonValue));
    }

    /**
     */
    async filesFileIdGet(requestParameters: FilesFileIdGetRequest): Promise<FileRecord> {
        const response = await this.filesFileIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async filesFileIdPutRaw(requestParameters: FilesFileIdPutRequest): Promise<runtime.ApiResponse<FileRecord>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesFileIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesFileIdPut.');
        }

        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new runtime.RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling filesFileIdPut.');
        }

        if (requestParameters.filesFileIdPutRequestBody === null || requestParameters.filesFileIdPutRequestBody === undefined) {
            throw new runtime.RequiredError('filesFileIdPutRequestBody','Required parameter requestParameters.filesFileIdPutRequestBody was null or undefined when calling filesFileIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/files/{fileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: FilesFileIdPutRequestBodyToJSON(requestParameters.filesFileIdPutRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => FileRecordFromJSON(jsonValue));
    }

    /**
     */
    async filesFileIdPut(requestParameters: FilesFileIdPutRequest): Promise<FileRecord> {
        const response = await this.filesFileIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async filesGetRaw(requestParameters: FilesGetRequest): Promise<runtime.ApiResponse<FilesGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.idGt !== undefined) {
            queryParameters['id__gt'] = requestParameters.idGt;
        }

        if (requestParameters.idLt !== undefined) {
            queryParameters['id__lt'] = requestParameters.idLt;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.userId !== undefined) {
            queryParameters['user_id'] = requestParameters.userId;
        }

        if (requestParameters.updatedAt !== undefined) {
            queryParameters['updated_at'] = (requestParameters.updatedAt as any).toISOString();
        }

        if (requestParameters.updatedAtGt !== undefined) {
            queryParameters['updated_at__gt'] = (requestParameters.updatedAtGt as any).toISOString();
        }

        if (requestParameters.updatedAtLt !== undefined) {
            queryParameters['updated_at__lt'] = (requestParameters.updatedAtLt as any).toISOString();
        }

        if (requestParameters.ordering !== undefined) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/files/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => FilesGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async filesGet(requestParameters: FilesGetRequest): Promise<FilesGetResponse> {
        const response = await this.filesGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async filesPostRaw(requestParameters: FilesPostRequest): Promise<runtime.ApiResponse<FileRecord>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesPost.');
        }

        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling filesPost.');
        }

        if (requestParameters.file === null || requestParameters.file === undefined) {
            throw new runtime.RequiredError('file','Required parameter requestParameters.file was null or undefined when calling filesPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.name !== undefined) {
            formParams.append('name', requestParameters.name as any);
        }

        if (requestParameters.file !== undefined) {
            formParams.append('file', requestParameters.file as any);
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/files/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => FileRecordFromJSON(jsonValue));
    }

    /**
     */
    async filesPost(requestParameters: FilesPostRequest): Promise<FileRecord> {
        const response = await this.filesPostRaw(requestParameters);
        return await response.value();
    }

}
