// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    FileRecord,
    FilesFileIdPutRequestBody,
    FilesGetResponse,
} from '../models';

export interface FilesFileIdDeleteRequest {
    spaceId: number;
    projectId: number;
    fileId: number;
}

export interface FilesFileIdGetRequest {
    spaceId: number;
    projectId: number;
    fileId: number;
}

export interface FilesFileIdPutRequest {
    spaceId: number;
    projectId: number;
    fileId: number;
    filesFileIdPutRequestBody: FilesFileIdPutRequestBody;
}

export interface FilesGetRequest {
    spaceId: number;
    projectId: number;
    page?: number;
    name?: string;
    userId?: number;
}

export interface FilesPostRequest {
    spaceId: number;
    projectId: number;
    name: string;
    file: Blob;
}

/**
 * no description
 */
export class FilesApi extends BaseAPI {

    /**
     */
    filesFileIdDelete(requestParameters: FilesFileIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesFileIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesFileIdDelete.');
        }

        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling filesFileIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/projects/{projectId}/files/{fileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    filesFileIdGet(requestParameters: FilesFileIdGetRequest): Observable<FileRecord> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesFileIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesFileIdGet.');
        }

        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling filesFileIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<FileRecord>({
            path: `/spaces/{spaceId}/projects/{projectId}/files/{fileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    filesFileIdPut(requestParameters: FilesFileIdPutRequest): Observable<FileRecord> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesFileIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesFileIdPut.');
        }

        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling filesFileIdPut.');
        }

        if (requestParameters.filesFileIdPutRequestBody === null || requestParameters.filesFileIdPutRequestBody === undefined) {
            throw new RequiredError('filesFileIdPutRequestBody','Required parameter requestParameters.filesFileIdPutRequestBody was null or undefined when calling filesFileIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<FileRecord>({
            path: `/spaces/{spaceId}/projects/{projectId}/files/{fileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.filesFileIdPutRequestBody,
        });
    }

    /**
     */
    filesGet(requestParameters: FilesGetRequest): Observable<FilesGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesGet.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.page !== undefined && requestParameters.page !== null) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.name !== undefined && requestParameters.name !== null) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.userId !== undefined && requestParameters.userId !== null) {
            queryParameters['user_id'] = requestParameters.userId;
        }

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<FilesGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/files/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    filesPost(requestParameters: FilesPostRequest): Observable<FileRecord> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling filesPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling filesPost.');
        }

        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new RequiredError('name','Required parameter requestParameters.name was null or undefined when calling filesPost.');
        }

        if (requestParameters.file === null || requestParameters.file === undefined) {
            throw new RequiredError('file','Required parameter requestParameters.file was null or undefined when calling filesPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const formData = new FormData();
        if (requestParameters.name !== undefined) {
            formData.append('name', requestParameters.name as any);
        }

        if (requestParameters.file !== undefined) {
            formData.append('file', requestParameters.file as any);
        }

        return this.request<FileRecord>({
            path: `/spaces/{spaceId}/projects/{projectId}/files/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formData,
        });
    }

}
