// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Note,
    NoteFromJSON,
    NoteToJSON,
    NoteStatus,
    NoteStatusFromJSON,
    NoteStatusToJSON,
    NotesGetResponse,
    NotesGetResponseFromJSON,
    NotesGetResponseToJSON,
    NotesNoteIdFavoritePostRequestBody,
    NotesNoteIdFavoritePostRequestBodyFromJSON,
    NotesNoteIdFavoritePostRequestBodyToJSON,
    NotesNoteIdPutRequestBody,
    NotesNoteIdPutRequestBodyFromJSON,
    NotesNoteIdPutRequestBodyToJSON,
    NotesPostRequestBody,
    NotesPostRequestBodyFromJSON,
    NotesPostRequestBodyToJSON,
    TasksStatusPostRequestBodyItem,
    TasksStatusPostRequestBodyItemFromJSON,
    TasksStatusPostRequestBodyItemToJSON,
    TasksTaskIdFavoriteGetResponse,
    TasksTaskIdFavoriteGetResponseFromJSON,
    TasksTaskIdFavoriteGetResponseToJSON,
} from '../models';

export interface NotesGetRequest {
    spaceId: number;
    projectId: number;
    page?: number;
    limit?: number;
    id?: number;
    idGt?: number;
    idLt?: number;
    subject?: string;
    status?: number;
    batonUser?: number;
    writeUser?: number;
    updatedAt?: Date;
    updatedAtGt?: Date;
    updatedAtLt?: Date;
    favorite?: boolean;
    ordering?: string;
}

export interface NotesNoteIdDeleteRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdFavoriteGetRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdFavoritePostRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    notesNoteIdFavoritePostRequestBody: NotesNoteIdFavoritePostRequestBody;
}

export interface NotesNoteIdGetRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdPutRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    notesNoteIdPutRequestBody: NotesNoteIdPutRequestBody;
}

export interface NotesPostRequest {
    spaceId: number;
    projectId: number;
    notesPostRequestBody: NotesPostRequestBody;
}

export interface NotesStatusGetRequest {
    spaceId: number;
    projectId: number;
}

export interface NotesStatusPostRequest {
    spaceId: number;
    projectId: number;
    tasksStatusPostRequestBodyItem: Array<TasksStatusPostRequestBodyItem>;
}

/**
 * no description
 */
export class NotesApi extends runtime.BaseAPI {

    /**
     */
    async notesGetRaw(requestParameters: NotesGetRequest): Promise<runtime.ApiResponse<NotesGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.idGt !== undefined) {
            queryParameters['id__gt'] = requestParameters.idGt;
        }

        if (requestParameters.idLt !== undefined) {
            queryParameters['id__lt'] = requestParameters.idLt;
        }

        if (requestParameters.subject !== undefined) {
            queryParameters['subject'] = requestParameters.subject;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.batonUser !== undefined) {
            queryParameters['baton_user'] = requestParameters.batonUser;
        }

        if (requestParameters.writeUser !== undefined) {
            queryParameters['write_user'] = requestParameters.writeUser;
        }

        if (requestParameters.updatedAt !== undefined) {
            queryParameters['updated_at'] = (requestParameters.updatedAt as any).toISOString();
        }

        if (requestParameters.updatedAtGt !== undefined) {
            queryParameters['updated_at__gt'] = (requestParameters.updatedAtGt as any).toISOString();
        }

        if (requestParameters.updatedAtLt !== undefined) {
            queryParameters['updated_at__lt'] = (requestParameters.updatedAtLt as any).toISOString();
        }

        if (requestParameters.favorite !== undefined) {
            queryParameters['favorite'] = requestParameters.favorite;
        }

        if (requestParameters.ordering !== undefined) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NotesGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async notesGet(requestParameters: NotesGetRequest): Promise<NotesGetResponse> {
        const response = await this.notesGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdDeleteRaw(requestParameters: NotesNoteIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdDelete.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async notesNoteIdDelete(requestParameters: NotesNoteIdDeleteRequest): Promise<void> {
        await this.notesNoteIdDeleteRaw(requestParameters);
    }

    /**
     */
    async notesNoteIdFavoriteGetRaw(requestParameters: NotesNoteIdFavoriteGetRequest): Promise<runtime.ApiResponse<TasksTaskIdFavoriteGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/favorite/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksTaskIdFavoriteGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdFavoriteGet(requestParameters: NotesNoteIdFavoriteGetRequest): Promise<TasksTaskIdFavoriteGetResponse> {
        const response = await this.notesNoteIdFavoriteGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdFavoritePostRaw(requestParameters: NotesNoteIdFavoritePostRequest): Promise<runtime.ApiResponse<TasksTaskIdFavoriteGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.notesNoteIdFavoritePostRequestBody === null || requestParameters.notesNoteIdFavoritePostRequestBody === undefined) {
            throw new runtime.RequiredError('notesNoteIdFavoritePostRequestBody','Required parameter requestParameters.notesNoteIdFavoritePostRequestBody was null or undefined when calling notesNoteIdFavoritePost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/favorite/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotesNoteIdFavoritePostRequestBodyToJSON(requestParameters.notesNoteIdFavoritePostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksTaskIdFavoriteGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdFavoritePost(requestParameters: NotesNoteIdFavoritePostRequest): Promise<TasksTaskIdFavoriteGetResponse> {
        const response = await this.notesNoteIdFavoritePostRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdGetRaw(requestParameters: NotesNoteIdGetRequest): Promise<runtime.ApiResponse<Note>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdGet.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdGet(requestParameters: NotesNoteIdGetRequest): Promise<Note> {
        const response = await this.notesNoteIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdPutRaw(requestParameters: NotesNoteIdPutRequest): Promise<runtime.ApiResponse<Note>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.notesNoteIdPutRequestBody === null || requestParameters.notesNoteIdPutRequestBody === undefined) {
            throw new runtime.RequiredError('notesNoteIdPutRequestBody','Required parameter requestParameters.notesNoteIdPutRequestBody was null or undefined when calling notesNoteIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NotesNoteIdPutRequestBodyToJSON(requestParameters.notesNoteIdPutRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdPut(requestParameters: NotesNoteIdPutRequest): Promise<Note> {
        const response = await this.notesNoteIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesPostRaw(requestParameters: NotesPostRequest): Promise<runtime.ApiResponse<Note>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesPost.');
        }

        if (requestParameters.notesPostRequestBody === null || requestParameters.notesPostRequestBody === undefined) {
            throw new runtime.RequiredError('notesPostRequestBody','Required parameter requestParameters.notesPostRequestBody was null or undefined when calling notesPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotesPostRequestBodyToJSON(requestParameters.notesPostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteFromJSON(jsonValue));
    }

    /**
     */
    async notesPost(requestParameters: NotesPostRequest): Promise<Note> {
        const response = await this.notesPostRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesStatusGetRaw(requestParameters: NotesStatusGetRequest): Promise<runtime.ApiResponse<Array<NoteStatus>>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesStatusGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesStatusGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/status/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NoteStatusFromJSON));
    }

    /**
     */
    async notesStatusGet(requestParameters: NotesStatusGetRequest): Promise<Array<NoteStatus>> {
        const response = await this.notesStatusGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesStatusPostRaw(requestParameters: NotesStatusPostRequest): Promise<runtime.ApiResponse<NoteStatus>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesStatusPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesStatusPost.');
        }

        if (requestParameters.tasksStatusPostRequestBodyItem === null || requestParameters.tasksStatusPostRequestBodyItem === undefined) {
            throw new runtime.RequiredError('tasksStatusPostRequestBodyItem','Required parameter requestParameters.tasksStatusPostRequestBodyItem was null or undefined when calling notesStatusPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/status/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.tasksStatusPostRequestBodyItem.map(TasksStatusPostRequestBodyItemToJSON),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteStatusFromJSON(jsonValue));
    }

    /**
     */
    async notesStatusPost(requestParameters: NotesStatusPostRequest): Promise<NoteStatus> {
        const response = await this.notesStatusPostRaw(requestParameters);
        return await response.value();
    }

}
