// tslint:disable
// eslint-disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Note,
    NoteFromJSON,
    NoteToJSON,
    NoteComment,
    NoteCommentFromJSON,
    NoteCommentToJSON,
    NoteCommmentsGetResponse,
    NoteCommmentsGetResponseFromJSON,
    NoteCommmentsGetResponseToJSON,
    NoteCommmentsNoteCommentIdPutRequestBody,
    NoteCommmentsNoteCommentIdPutRequestBodyFromJSON,
    NoteCommmentsNoteCommentIdPutRequestBodyToJSON,
    NoteCommmentsPostRequestBody,
    NoteCommmentsPostRequestBodyFromJSON,
    NoteCommmentsPostRequestBodyToJSON,
    NoteStatus,
    NoteStatusFromJSON,
    NoteStatusToJSON,
    NotesGetResponse,
    NotesGetResponseFromJSON,
    NotesGetResponseToJSON,
    NotesNoteIdFavoritePostRequestBody,
    NotesNoteIdFavoritePostRequestBodyFromJSON,
    NotesNoteIdFavoritePostRequestBodyToJSON,
    NotesNoteIdPatchRequestBody,
    NotesNoteIdPatchRequestBodyFromJSON,
    NotesNoteIdPatchRequestBodyToJSON,
    NotesNoteIdPriorityPostRequestBody,
    NotesNoteIdPriorityPostRequestBodyFromJSON,
    NotesNoteIdPriorityPostRequestBodyToJSON,
    NotesNoteIdPutRequestBody,
    NotesNoteIdPutRequestBodyFromJSON,
    NotesNoteIdPutRequestBodyToJSON,
    NotesPostRequestBody,
    NotesPostRequestBodyFromJSON,
    NotesPostRequestBodyToJSON,
    NotesSummariesGetResponse,
    NotesSummariesGetResponseFromJSON,
    NotesSummariesGetResponseToJSON,
    TasksStatusPostRequestBodyItem,
    TasksStatusPostRequestBodyItemFromJSON,
    TasksStatusPostRequestBodyItemToJSON,
    TasksTaskIdFavoriteGetResponse,
    TasksTaskIdFavoriteGetResponseFromJSON,
    TasksTaskIdFavoriteGetResponseToJSON,
} from '../models';

export interface NoteCommmentsGetRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    page?: number;
    limit?: number;
    id?: number;
    idGt?: number;
    idLt?: number;
    createdAt?: Date;
    createdAtGt?: Date;
    createdAtLt?: Date;
    ordering?: string;
}

export interface NoteCommmentsNoteCommentIdDeleteRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    noteCommentId: number;
}

export interface NoteCommmentsNoteCommentIdGetRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    noteCommentId: number;
}

export interface NoteCommmentsNoteCommentIdPutRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    noteCommentId: number;
    noteCommmentsNoteCommentIdPutRequestBody: NoteCommmentsNoteCommentIdPutRequestBody;
}

export interface NoteCommmentsPostRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    noteCommmentsPostRequestBody: NoteCommmentsPostRequestBody;
}

export interface NotesGetRequest {
    spaceId: number;
    projectId: number;
    page?: number;
    limit?: number;
    id?: Array<number>;
    parent?: number;
    root?: boolean;
    subject?: string;
    status?: Array<number>;
    batonUser?: Array<number>;
    writeUser?: number;
    chargeUsers?: Array<number>;
    favorite?: boolean;
    ordering?: string;
}

export interface NotesNoteIdDeleteRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdFavoriteGetRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdFavoritePostRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    notesNoteIdFavoritePostRequestBody: NotesNoteIdFavoritePostRequestBody;
}

export interface NotesNoteIdGetRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdPatchRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    notesNoteIdPatchRequestBody: NotesNoteIdPatchRequestBody;
}

export interface NotesNoteIdPriorityPostRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    notesNoteIdPriorityPostRequestBody: NotesNoteIdPriorityPostRequestBody;
}

export interface NotesNoteIdPutRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    notesNoteIdPutRequestBody: NotesNoteIdPutRequestBody;
}

export interface NotesPostRequest {
    spaceId: number;
    projectId: number;
    notesPostRequestBody: NotesPostRequestBody;
}

export interface NotesStatusGetRequest {
    spaceId: number;
    projectId: number;
}

export interface NotesStatusPostRequest {
    spaceId: number;
    projectId: number;
    tasksStatusPostRequestBodyItem: Array<TasksStatusPostRequestBodyItem>;
}

export interface NotesSummariesGetRequest {
    spaceId: number;
    projectId: number;
    page?: number;
    limit?: number;
    id?: Array<number>;
    parent?: number;
    root?: boolean;
    subject?: string;
    status?: Array<number>;
    batonUser?: Array<number>;
    writeUser?: number;
    chargeUsers?: Array<number>;
    favorite?: boolean;
    ordering?: string;
}

/**
 * no description
 */
export class NotesApi extends runtime.BaseAPI {

    /**
     */
    async noteCommmentsGetRaw(requestParameters: NoteCommmentsGetRequest): Promise<runtime.ApiResponse<NoteCommmentsGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling noteCommmentsGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling noteCommmentsGet.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteCommmentsGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.idGt !== undefined) {
            queryParameters['id__gt'] = requestParameters.idGt;
        }

        if (requestParameters.idLt !== undefined) {
            queryParameters['id__lt'] = requestParameters.idLt;
        }

        if (requestParameters.createdAt !== undefined) {
            queryParameters['created_at'] = (requestParameters.createdAt as any).toISOString();
        }

        if (requestParameters.createdAtGt !== undefined) {
            queryParameters['created_at__gt'] = (requestParameters.createdAtGt as any).toISOString();
        }

        if (requestParameters.createdAtLt !== undefined) {
            queryParameters['created_at__lt'] = (requestParameters.createdAtLt as any).toISOString();
        }

        if (requestParameters.ordering !== undefined) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/comments/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteCommmentsGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async noteCommmentsGet(requestParameters: NoteCommmentsGetRequest): Promise<NoteCommmentsGetResponse> {
        const response = await this.noteCommmentsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async noteCommmentsNoteCommentIdDeleteRaw(requestParameters: NoteCommmentsNoteCommentIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling noteCommmentsNoteCommentIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling noteCommmentsNoteCommentIdDelete.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteCommmentsNoteCommentIdDelete.');
        }

        if (requestParameters.noteCommentId === null || requestParameters.noteCommentId === undefined) {
            throw new runtime.RequiredError('noteCommentId','Required parameter requestParameters.noteCommentId was null or undefined when calling noteCommmentsNoteCommentIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/comments/{noteCommentId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))).replace(`{${"noteCommentId"}}`, encodeURIComponent(String(requestParameters.noteCommentId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async noteCommmentsNoteCommentIdDelete(requestParameters: NoteCommmentsNoteCommentIdDeleteRequest): Promise<void> {
        await this.noteCommmentsNoteCommentIdDeleteRaw(requestParameters);
    }

    /**
     */
    async noteCommmentsNoteCommentIdGetRaw(requestParameters: NoteCommmentsNoteCommentIdGetRequest): Promise<runtime.ApiResponse<NoteComment>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling noteCommmentsNoteCommentIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling noteCommmentsNoteCommentIdGet.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteCommmentsNoteCommentIdGet.');
        }

        if (requestParameters.noteCommentId === null || requestParameters.noteCommentId === undefined) {
            throw new runtime.RequiredError('noteCommentId','Required parameter requestParameters.noteCommentId was null or undefined when calling noteCommmentsNoteCommentIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/comments/{noteCommentId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))).replace(`{${"noteCommentId"}}`, encodeURIComponent(String(requestParameters.noteCommentId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteCommentFromJSON(jsonValue));
    }

    /**
     */
    async noteCommmentsNoteCommentIdGet(requestParameters: NoteCommmentsNoteCommentIdGetRequest): Promise<NoteComment> {
        const response = await this.noteCommmentsNoteCommentIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async noteCommmentsNoteCommentIdPutRaw(requestParameters: NoteCommmentsNoteCommentIdPutRequest): Promise<runtime.ApiResponse<NoteComment>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling noteCommmentsNoteCommentIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling noteCommmentsNoteCommentIdPut.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteCommmentsNoteCommentIdPut.');
        }

        if (requestParameters.noteCommentId === null || requestParameters.noteCommentId === undefined) {
            throw new runtime.RequiredError('noteCommentId','Required parameter requestParameters.noteCommentId was null or undefined when calling noteCommmentsNoteCommentIdPut.');
        }

        if (requestParameters.noteCommmentsNoteCommentIdPutRequestBody === null || requestParameters.noteCommmentsNoteCommentIdPutRequestBody === undefined) {
            throw new runtime.RequiredError('noteCommmentsNoteCommentIdPutRequestBody','Required parameter requestParameters.noteCommmentsNoteCommentIdPutRequestBody was null or undefined when calling noteCommmentsNoteCommentIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/comments/{noteCommentId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))).replace(`{${"noteCommentId"}}`, encodeURIComponent(String(requestParameters.noteCommentId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NoteCommmentsNoteCommentIdPutRequestBodyToJSON(requestParameters.noteCommmentsNoteCommentIdPutRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteCommentFromJSON(jsonValue));
    }

    /**
     */
    async noteCommmentsNoteCommentIdPut(requestParameters: NoteCommmentsNoteCommentIdPutRequest): Promise<NoteComment> {
        const response = await this.noteCommmentsNoteCommentIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async noteCommmentsPostRaw(requestParameters: NoteCommmentsPostRequest): Promise<runtime.ApiResponse<NoteComment>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling noteCommmentsPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling noteCommmentsPost.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteCommmentsPost.');
        }

        if (requestParameters.noteCommmentsPostRequestBody === null || requestParameters.noteCommmentsPostRequestBody === undefined) {
            throw new runtime.RequiredError('noteCommmentsPostRequestBody','Required parameter requestParameters.noteCommmentsPostRequestBody was null or undefined when calling noteCommmentsPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/comments/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NoteCommmentsPostRequestBodyToJSON(requestParameters.noteCommmentsPostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteCommentFromJSON(jsonValue));
    }

    /**
     */
    async noteCommmentsPost(requestParameters: NoteCommmentsPostRequest): Promise<NoteComment> {
        const response = await this.noteCommmentsPostRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesGetRaw(requestParameters: NotesGetRequest): Promise<runtime.ApiResponse<NotesGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.id) {
            queryParameters['id'] = requestParameters.id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.parent !== undefined) {
            queryParameters['parent'] = requestParameters.parent;
        }

        if (requestParameters.root !== undefined) {
            queryParameters['root'] = requestParameters.root;
        }

        if (requestParameters.subject !== undefined) {
            queryParameters['subject'] = requestParameters.subject;
        }

        if (requestParameters.status) {
            queryParameters['status'] = requestParameters.status.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.batonUser) {
            queryParameters['baton_user'] = requestParameters.batonUser.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.writeUser !== undefined) {
            queryParameters['write_user'] = requestParameters.writeUser;
        }

        if (requestParameters.chargeUsers) {
            queryParameters['charge_users'] = requestParameters.chargeUsers.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.favorite !== undefined) {
            queryParameters['favorite'] = requestParameters.favorite;
        }

        if (requestParameters.ordering !== undefined) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NotesGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async notesGet(requestParameters: NotesGetRequest): Promise<NotesGetResponse> {
        const response = await this.notesGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdDeleteRaw(requestParameters: NotesNoteIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdDelete.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async notesNoteIdDelete(requestParameters: NotesNoteIdDeleteRequest): Promise<void> {
        await this.notesNoteIdDeleteRaw(requestParameters);
    }

    /**
     */
    async notesNoteIdFavoriteGetRaw(requestParameters: NotesNoteIdFavoriteGetRequest): Promise<runtime.ApiResponse<TasksTaskIdFavoriteGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/favorite/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksTaskIdFavoriteGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdFavoriteGet(requestParameters: NotesNoteIdFavoriteGetRequest): Promise<TasksTaskIdFavoriteGetResponse> {
        const response = await this.notesNoteIdFavoriteGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdFavoritePostRaw(requestParameters: NotesNoteIdFavoritePostRequest): Promise<runtime.ApiResponse<TasksTaskIdFavoriteGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.notesNoteIdFavoritePostRequestBody === null || requestParameters.notesNoteIdFavoritePostRequestBody === undefined) {
            throw new runtime.RequiredError('notesNoteIdFavoritePostRequestBody','Required parameter requestParameters.notesNoteIdFavoritePostRequestBody was null or undefined when calling notesNoteIdFavoritePost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/favorite/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotesNoteIdFavoritePostRequestBodyToJSON(requestParameters.notesNoteIdFavoritePostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksTaskIdFavoriteGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdFavoritePost(requestParameters: NotesNoteIdFavoritePostRequest): Promise<TasksTaskIdFavoriteGetResponse> {
        const response = await this.notesNoteIdFavoritePostRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdGetRaw(requestParameters: NotesNoteIdGetRequest): Promise<runtime.ApiResponse<Note>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdGet.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdGet(requestParameters: NotesNoteIdGetRequest): Promise<Note> {
        const response = await this.notesNoteIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdPatchRaw(requestParameters: NotesNoteIdPatchRequest): Promise<runtime.ApiResponse<Note>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdPatch.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdPatch.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdPatch.');
        }

        if (requestParameters.notesNoteIdPatchRequestBody === null || requestParameters.notesNoteIdPatchRequestBody === undefined) {
            throw new runtime.RequiredError('notesNoteIdPatchRequestBody','Required parameter requestParameters.notesNoteIdPatchRequestBody was null or undefined when calling notesNoteIdPatch.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: NotesNoteIdPatchRequestBodyToJSON(requestParameters.notesNoteIdPatchRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdPatch(requestParameters: NotesNoteIdPatchRequest): Promise<Note> {
        const response = await this.notesNoteIdPatchRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesNoteIdPriorityPostRaw(requestParameters: NotesNoteIdPriorityPostRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdPriorityPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdPriorityPost.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdPriorityPost.');
        }

        if (requestParameters.notesNoteIdPriorityPostRequestBody === null || requestParameters.notesNoteIdPriorityPostRequestBody === undefined) {
            throw new runtime.RequiredError('notesNoteIdPriorityPostRequestBody','Required parameter requestParameters.notesNoteIdPriorityPostRequestBody was null or undefined when calling notesNoteIdPriorityPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/priority/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotesNoteIdPriorityPostRequestBodyToJSON(requestParameters.notesNoteIdPriorityPostRequestBody),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async notesNoteIdPriorityPost(requestParameters: NotesNoteIdPriorityPostRequest): Promise<void> {
        await this.notesNoteIdPriorityPostRaw(requestParameters);
    }

    /**
     */
    async notesNoteIdPutRaw(requestParameters: NotesNoteIdPutRequest): Promise<runtime.ApiResponse<Note>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.notesNoteIdPutRequestBody === null || requestParameters.notesNoteIdPutRequestBody === undefined) {
            throw new runtime.RequiredError('notesNoteIdPutRequestBody','Required parameter requestParameters.notesNoteIdPutRequestBody was null or undefined when calling notesNoteIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NotesNoteIdPutRequestBodyToJSON(requestParameters.notesNoteIdPutRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteFromJSON(jsonValue));
    }

    /**
     */
    async notesNoteIdPut(requestParameters: NotesNoteIdPutRequest): Promise<Note> {
        const response = await this.notesNoteIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesPostRaw(requestParameters: NotesPostRequest): Promise<runtime.ApiResponse<Note>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesPost.');
        }

        if (requestParameters.notesPostRequestBody === null || requestParameters.notesPostRequestBody === undefined) {
            throw new runtime.RequiredError('notesPostRequestBody','Required parameter requestParameters.notesPostRequestBody was null or undefined when calling notesPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotesPostRequestBodyToJSON(requestParameters.notesPostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteFromJSON(jsonValue));
    }

    /**
     */
    async notesPost(requestParameters: NotesPostRequest): Promise<Note> {
        const response = await this.notesPostRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesStatusGetRaw(requestParameters: NotesStatusGetRequest): Promise<runtime.ApiResponse<Array<NoteStatus>>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesStatusGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesStatusGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/status/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NoteStatusFromJSON));
    }

    /**
     */
    async notesStatusGet(requestParameters: NotesStatusGetRequest): Promise<Array<NoteStatus>> {
        const response = await this.notesStatusGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesStatusPostRaw(requestParameters: NotesStatusPostRequest): Promise<runtime.ApiResponse<Array<NoteStatus>>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesStatusPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesStatusPost.');
        }

        if (requestParameters.tasksStatusPostRequestBodyItem === null || requestParameters.tasksStatusPostRequestBodyItem === undefined) {
            throw new runtime.RequiredError('tasksStatusPostRequestBodyItem','Required parameter requestParameters.tasksStatusPostRequestBodyItem was null or undefined when calling notesStatusPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/status/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.tasksStatusPostRequestBodyItem.map(TasksStatusPostRequestBodyItemToJSON),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NoteStatusFromJSON));
    }

    /**
     */
    async notesStatusPost(requestParameters: NotesStatusPostRequest): Promise<Array<NoteStatus>> {
        const response = await this.notesStatusPostRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async notesSummariesGetRaw(requestParameters: NotesSummariesGetRequest): Promise<runtime.ApiResponse<NotesSummariesGetResponse>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesSummariesGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesSummariesGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.id) {
            queryParameters['id'] = requestParameters.id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.parent !== undefined) {
            queryParameters['parent'] = requestParameters.parent;
        }

        if (requestParameters.root !== undefined) {
            queryParameters['root'] = requestParameters.root;
        }

        if (requestParameters.subject !== undefined) {
            queryParameters['subject'] = requestParameters.subject;
        }

        if (requestParameters.status) {
            queryParameters['status'] = requestParameters.status.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.batonUser) {
            queryParameters['baton_user'] = requestParameters.batonUser.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.writeUser !== undefined) {
            queryParameters['write_user'] = requestParameters.writeUser;
        }

        if (requestParameters.chargeUsers) {
            queryParameters['charge_users'] = requestParameters.chargeUsers.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.favorite !== undefined) {
            queryParameters['favorite'] = requestParameters.favorite;
        }

        if (requestParameters.ordering !== undefined) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/summaries/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NotesSummariesGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async notesSummariesGet(requestParameters: NotesSummariesGetRequest): Promise<NotesSummariesGetResponse> {
        const response = await this.notesSummariesGetRaw(requestParameters);
        return await response.value();
    }

}
