// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    Note,
    NoteStatus,
    NotesGetResponse,
    NotesNoteIdFavoriteGetResponse,
    NotesNoteIdFavoritePostRequestBody,
    NotesNoteIdPutRequestBody,
    NotesPostRequestBody,
    TasksStatusPostRequestBodyItem,
} from '../models';

export interface NotesGetRequest {
    spaceId: number;
    projectId: number;
    page?: number;
    limit?: number;
    id?: number;
    idGt?: number;
    idLt?: number;
    subject?: string;
    status?: number;
    batonUser?: number;
    writeUser?: number;
    updatedAt?: Date;
    updatedAtGt?: Date;
    updatedAtLt?: Date;
    favorite?: boolean;
    ordering?: string;
}

export interface NotesNoteIdDeleteRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdFavoriteGetRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdFavoritePostRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    notesNoteIdFavoritePostRequestBody: NotesNoteIdFavoritePostRequestBody;
}

export interface NotesNoteIdGetRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
}

export interface NotesNoteIdPutRequest {
    spaceId: number;
    projectId: number;
    noteId: number;
    notesNoteIdPutRequestBody: NotesNoteIdPutRequestBody;
}

export interface NotesPostRequest {
    spaceId: number;
    projectId: number;
    notesPostRequestBody: NotesPostRequestBody;
}

export interface NotesStatusGetRequest {
    spaceId: number;
    projectId: number;
}

export interface NotesStatusPostRequest {
    spaceId: number;
    projectId: number;
    tasksStatusPostRequestBodyItem: Array<TasksStatusPostRequestBodyItem>;
}

/**
 * no description
 */
export class NotesApi extends BaseAPI {

    /**
     */
    notesGet(requestParameters: NotesGetRequest): Observable<NotesGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesGet.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.page !== undefined && requestParameters.page !== null) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined && requestParameters.limit !== null) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.id !== undefined && requestParameters.id !== null) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.idGt !== undefined && requestParameters.idGt !== null) {
            queryParameters['id__gt'] = requestParameters.idGt;
        }

        if (requestParameters.idLt !== undefined && requestParameters.idLt !== null) {
            queryParameters['id__lt'] = requestParameters.idLt;
        }

        if (requestParameters.subject !== undefined && requestParameters.subject !== null) {
            queryParameters['subject'] = requestParameters.subject;
        }

        if (requestParameters.status !== undefined && requestParameters.status !== null) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.batonUser !== undefined && requestParameters.batonUser !== null) {
            queryParameters['baton_user'] = requestParameters.batonUser;
        }

        if (requestParameters.writeUser !== undefined && requestParameters.writeUser !== null) {
            queryParameters['write_user'] = requestParameters.writeUser;
        }

        if (requestParameters.updatedAt !== undefined && requestParameters.updatedAt !== null) {
            queryParameters['updated_at'] = (requestParameters.updatedAt as any).toISOString();
        }

        if (requestParameters.updatedAtGt !== undefined && requestParameters.updatedAtGt !== null) {
            queryParameters['updated_at__gt'] = (requestParameters.updatedAtGt as any).toISOString();
        }

        if (requestParameters.updatedAtLt !== undefined && requestParameters.updatedAtLt !== null) {
            queryParameters['updated_at__lt'] = (requestParameters.updatedAtLt as any).toISOString();
        }

        if (requestParameters.favorite !== undefined && requestParameters.favorite !== null) {
            queryParameters['favorite'] = requestParameters.favorite;
        }

        if (requestParameters.ordering !== undefined && requestParameters.ordering !== null) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<NotesGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    notesNoteIdDelete(requestParameters: NotesNoteIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdDelete.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    notesNoteIdFavoriteGet(requestParameters: NotesNoteIdFavoriteGetRequest): Observable<NotesNoteIdFavoriteGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdFavoriteGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<NotesNoteIdFavoriteGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/favorite/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    notesNoteIdFavoritePost(requestParameters: NotesNoteIdFavoritePostRequest): Observable<NotesNoteIdFavoriteGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdFavoritePost.');
        }

        if (requestParameters.notesNoteIdFavoritePostRequestBody === null || requestParameters.notesNoteIdFavoritePostRequestBody === undefined) {
            throw new RequiredError('notesNoteIdFavoritePostRequestBody','Required parameter requestParameters.notesNoteIdFavoritePostRequestBody was null or undefined when calling notesNoteIdFavoritePost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<NotesNoteIdFavoriteGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/favorite/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.notesNoteIdFavoritePostRequestBody,
        });
    }

    /**
     */
    notesNoteIdGet(requestParameters: NotesNoteIdGetRequest): Observable<Note> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdGet.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Note>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    notesNoteIdPut(requestParameters: NotesNoteIdPutRequest): Observable<Note> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling notesNoteIdPut.');
        }

        if (requestParameters.notesNoteIdPutRequestBody === null || requestParameters.notesNoteIdPutRequestBody === undefined) {
            throw new RequiredError('notesNoteIdPutRequestBody','Required parameter requestParameters.notesNoteIdPutRequestBody was null or undefined when calling notesNoteIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Note>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/{noteId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.notesNoteIdPutRequestBody,
        });
    }

    /**
     */
    notesPost(requestParameters: NotesPostRequest): Observable<Note> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesPost.');
        }

        if (requestParameters.notesPostRequestBody === null || requestParameters.notesPostRequestBody === undefined) {
            throw new RequiredError('notesPostRequestBody','Required parameter requestParameters.notesPostRequestBody was null or undefined when calling notesPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Note>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.notesPostRequestBody,
        });
    }

    /**
     */
    notesStatusGet(requestParameters: NotesStatusGetRequest): Observable<Array<NoteStatus>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesStatusGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesStatusGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Array<NoteStatus>>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/status/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    notesStatusPost(requestParameters: NotesStatusPostRequest): Observable<NoteStatus> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling notesStatusPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling notesStatusPost.');
        }

        if (requestParameters.tasksStatusPostRequestBodyItem === null || requestParameters.tasksStatusPostRequestBodyItem === undefined) {
            throw new RequiredError('tasksStatusPostRequestBodyItem','Required parameter requestParameters.tasksStatusPostRequestBodyItem was null or undefined when calling notesStatusPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<NoteStatus>({
            path: `/spaces/{spaceId}/projects/{projectId}/notes/status/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.tasksStatusPostRequestBodyItem,
        });
    }

}
