// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    Project,
    ProjectUser,
    ProjectsGetResponse,
    ProjectsPostRequestBody,
    ProjectsProjectIdPutRequestBody,
    ProjectsProjectIdUsersGetResponse,
    ProjectsProjectIdUsersPostRequestBody,
    ProjectsProjectIdUsersUserIdPutRequestBody,
} from '../models';

export interface ProjectsGetRequest {
    spaceId: number;
    page?: number;
    displayName?: string;
    userId?: number;
}

export interface ProjectsPostRequest {
    spaceId: number;
    projectsPostRequestBody: ProjectsPostRequestBody;
}

export interface ProjectsProjectIdDeleteRequest {
    spaceId: number;
    projectId: number;
}

export interface ProjectsProjectIdGetRequest {
    spaceId: number;
    projectId: number;
}

export interface ProjectsProjectIdPutRequest {
    spaceId: number;
    projectId: number;
    projectsProjectIdPutRequestBody: ProjectsProjectIdPutRequestBody;
}

export interface ProjectsProjectIdUsersGetRequest {
    spaceId: number;
    projectId: number;
    page?: number;
    account?: string;
    displayName?: string;
}

export interface ProjectsProjectIdUsersPostRequest {
    spaceId: number;
    projectId: number;
    projectsProjectIdUsersPostRequestBody: ProjectsProjectIdUsersPostRequestBody;
}

export interface ProjectsProjectIdUsersUserIdDeleteRequest {
    spaceId: number;
    projectId: number;
    userId: number;
}

export interface ProjectsProjectIdUsersUserIdGetRequest {
    spaceId: number;
    projectId: number;
    userId: number;
}

export interface ProjectsProjectIdUsersUserIdPutRequest {
    spaceId: number;
    projectId: number;
    userId: number;
    projectsProjectIdUsersUserIdPutRequestBody: ProjectsProjectIdUsersUserIdPutRequestBody;
}

/**
 * no description
 */
export class ProjectsApi extends BaseAPI {

    /**
     */
    projectsGet(requestParameters: ProjectsGetRequest): Observable<ProjectsGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsGet.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.page !== undefined && requestParameters.page !== null) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.displayName !== undefined && requestParameters.displayName !== null) {
            queryParameters['display_name'] = requestParameters.displayName;
        }

        if (requestParameters.userId !== undefined && requestParameters.userId !== null) {
            queryParameters['user_id'] = requestParameters.userId;
        }

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<ProjectsGetResponse>({
            path: `/spaces/{spaceId}/projects/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    projectsPost(requestParameters: ProjectsPostRequest): Observable<Project> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsPost.');
        }

        if (requestParameters.projectsPostRequestBody === null || requestParameters.projectsPostRequestBody === undefined) {
            throw new RequiredError('projectsPostRequestBody','Required parameter requestParameters.projectsPostRequestBody was null or undefined when calling projectsPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Project>({
            path: `/spaces/{spaceId}/projects/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.projectsPostRequestBody,
        });
    }

    /**
     */
    projectsProjectIdDelete(requestParameters: ProjectsProjectIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsProjectIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling projectsProjectIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/projects/{projectId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    projectsProjectIdGet(requestParameters: ProjectsProjectIdGetRequest): Observable<Project> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsProjectIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling projectsProjectIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Project>({
            path: `/spaces/{spaceId}/projects/{projectId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    projectsProjectIdPut(requestParameters: ProjectsProjectIdPutRequest): Observable<Project> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsProjectIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling projectsProjectIdPut.');
        }

        if (requestParameters.projectsProjectIdPutRequestBody === null || requestParameters.projectsProjectIdPutRequestBody === undefined) {
            throw new RequiredError('projectsProjectIdPutRequestBody','Required parameter requestParameters.projectsProjectIdPutRequestBody was null or undefined when calling projectsProjectIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Project>({
            path: `/spaces/{spaceId}/projects/{projectId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.projectsProjectIdPutRequestBody,
        });
    }

    /**
     */
    projectsProjectIdUsersGet(requestParameters: ProjectsProjectIdUsersGetRequest): Observable<ProjectsProjectIdUsersGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsProjectIdUsersGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling projectsProjectIdUsersGet.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.page !== undefined && requestParameters.page !== null) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.account !== undefined && requestParameters.account !== null) {
            queryParameters['account'] = requestParameters.account;
        }

        if (requestParameters.displayName !== undefined && requestParameters.displayName !== null) {
            queryParameters['display_name'] = requestParameters.displayName;
        }

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<ProjectsProjectIdUsersGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/users/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    projectsProjectIdUsersPost(requestParameters: ProjectsProjectIdUsersPostRequest): Observable<ProjectUser> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsProjectIdUsersPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling projectsProjectIdUsersPost.');
        }

        if (requestParameters.projectsProjectIdUsersPostRequestBody === null || requestParameters.projectsProjectIdUsersPostRequestBody === undefined) {
            throw new RequiredError('projectsProjectIdUsersPostRequestBody','Required parameter requestParameters.projectsProjectIdUsersPostRequestBody was null or undefined when calling projectsProjectIdUsersPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<ProjectUser>({
            path: `/spaces/{spaceId}/projects/{projectId}/users/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.projectsProjectIdUsersPostRequestBody,
        });
    }

    /**
     */
    projectsProjectIdUsersUserIdDelete(requestParameters: ProjectsProjectIdUsersUserIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsProjectIdUsersUserIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling projectsProjectIdUsersUserIdDelete.');
        }

        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling projectsProjectIdUsersUserIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/projects/{projectId}/users/{userId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    projectsProjectIdUsersUserIdGet(requestParameters: ProjectsProjectIdUsersUserIdGetRequest): Observable<ProjectUser> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsProjectIdUsersUserIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling projectsProjectIdUsersUserIdGet.');
        }

        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling projectsProjectIdUsersUserIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<ProjectUser>({
            path: `/spaces/{spaceId}/projects/{projectId}/users/{userId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    projectsProjectIdUsersUserIdPut(requestParameters: ProjectsProjectIdUsersUserIdPutRequest): Observable<ProjectUser> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling projectsProjectIdUsersUserIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling projectsProjectIdUsersUserIdPut.');
        }

        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling projectsProjectIdUsersUserIdPut.');
        }

        if (requestParameters.projectsProjectIdUsersUserIdPutRequestBody === null || requestParameters.projectsProjectIdUsersUserIdPutRequestBody === undefined) {
            throw new RequiredError('projectsProjectIdUsersUserIdPutRequestBody','Required parameter requestParameters.projectsProjectIdUsersUserIdPutRequestBody was null or undefined when calling projectsProjectIdUsersUserIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<ProjectUser>({
            path: `/spaces/{spaceId}/projects/{projectId}/users/{userId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.projectsProjectIdUsersUserIdPutRequestBody,
        });
    }

}
