// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    InlineObject,
    InlineObject1,
    InlineObject2,
    InlineObject3,
    InlineResponse200,
    InlineResponse2001,
    Space,
    SpaceUser,
} from '../models';

export interface SpacesConfirmPostRequest {
    inlineObject: InlineObject;
}

export interface SpacesGetRequest {
    page?: number;
    account?: string;
    displayName?: string;
}

export interface SpacesPostRequest {
    inlineObject1: InlineObject1;
}

export interface SpacesSpaceIdDeleteRequest {
    spaceId: number;
}

export interface SpacesSpaceIdGetRequest {
    spaceId: number;
}

export interface SpacesSpaceIdPutRequest {
    spaceId: number;
    inlineObject2: InlineObject2;
}

export interface SpacesSpaceIdUsersGetRequest {
    spaceId: number;
    page?: number;
    account?: string;
    displayName?: string;
    spaceRoleId?: number;
}

export interface SpacesSpaceIdUsersUserIdDeleteRequest {
    spaceId: number;
    userId: number;
}

export interface SpacesSpaceIdUsersUserIdGetRequest {
    spaceId: number;
    userId: number;
}

export interface SpacesSpaceIdUsersUserIdPutRequest {
    spaceId: number;
    userId: number;
    inlineObject3: InlineObject3;
}

/**
 * no description
 */
export class SpacesApi extends BaseAPI {

    /**
     * スペース登録用メール認証メッセージ送信
     */
    spacesConfirmPost(requestParameters: SpacesConfirmPostRequest): Observable<void> {
        if (requestParameters.inlineObject === null || requestParameters.inlineObject === undefined) {
            throw new RequiredError('inlineObject','Required parameter requestParameters.inlineObject was null or undefined when calling spacesConfirmPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return this.request<void>({
            path: `/spaces/confirm/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.inlineObject,
        });
    }

    /**
     */
    spacesGet(requestParameters: SpacesGetRequest): Observable<InlineResponse200> {
        const queryParameters: HttpQuery = {};

        if (requestParameters.page !== undefined && requestParameters.page !== null) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.account !== undefined && requestParameters.account !== null) {
            queryParameters['account'] = requestParameters.account;
        }

        if (requestParameters.displayName !== undefined && requestParameters.displayName !== null) {
            queryParameters['display_name'] = requestParameters.displayName;
        }

        const headerParameters: HttpHeaders = {};

        return this.request<InlineResponse200>({
            path: `/spaces/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     * メール認証通過後、スペース登録
     */
    spacesPost(requestParameters: SpacesPostRequest): Observable<Space> {
        if (requestParameters.inlineObject1 === null || requestParameters.inlineObject1 === undefined) {
            throw new RequiredError('inlineObject1','Required parameter requestParameters.inlineObject1 was null or undefined when calling spacesPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return this.request<Space>({
            path: `/spaces/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.inlineObject1,
        });
    }

    /**
     */
    spacesSpaceIdDelete(requestParameters: SpacesSpaceIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling spacesSpaceIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    spacesSpaceIdGet(requestParameters: SpacesSpaceIdGetRequest): Observable<Space> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling spacesSpaceIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        return this.request<Space>({
            path: `/spaces/{spaceId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    spacesSpaceIdPut(requestParameters: SpacesSpaceIdPutRequest): Observable<Space> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling spacesSpaceIdPut.');
        }

        if (requestParameters.inlineObject2 === null || requestParameters.inlineObject2 === undefined) {
            throw new RequiredError('inlineObject2','Required parameter requestParameters.inlineObject2 was null or undefined when calling spacesSpaceIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Space>({
            path: `/spaces/{spaceId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.inlineObject2,
        });
    }

    /**
     */
    spacesSpaceIdUsersGet(requestParameters: SpacesSpaceIdUsersGetRequest): Observable<InlineResponse2001> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling spacesSpaceIdUsersGet.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.page !== undefined && requestParameters.page !== null) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.account !== undefined && requestParameters.account !== null) {
            queryParameters['account'] = requestParameters.account;
        }

        if (requestParameters.displayName !== undefined && requestParameters.displayName !== null) {
            queryParameters['display_name'] = requestParameters.displayName;
        }

        if (requestParameters.spaceRoleId !== undefined && requestParameters.spaceRoleId !== null) {
            queryParameters['space_role_id'] = requestParameters.spaceRoleId;
        }

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<InlineResponse2001>({
            path: `/spaces/{spaceId}/users/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    spacesSpaceIdUsersUserIdDelete(requestParameters: SpacesSpaceIdUsersUserIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling spacesSpaceIdUsersUserIdDelete.');
        }

        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling spacesSpaceIdUsersUserIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/users/{userId}`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    spacesSpaceIdUsersUserIdGet(requestParameters: SpacesSpaceIdUsersUserIdGetRequest): Observable<SpaceUser> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling spacesSpaceIdUsersUserIdGet.');
        }

        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling spacesSpaceIdUsersUserIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<SpaceUser>({
            path: `/spaces/{spaceId}/users/{userId}`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    spacesSpaceIdUsersUserIdPut(requestParameters: SpacesSpaceIdUsersUserIdPutRequest): Observable<SpaceUser> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling spacesSpaceIdUsersUserIdPut.');
        }

        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling spacesSpaceIdUsersUserIdPut.');
        }

        if (requestParameters.inlineObject3 === null || requestParameters.inlineObject3 === undefined) {
            throw new RequiredError('inlineObject3','Required parameter requestParameters.inlineObject3 was null or undefined when calling spacesSpaceIdUsersUserIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<SpaceUser>({
            path: `/spaces/{spaceId}/users/{userId}`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.inlineObject3,
        });
    }

}
