// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    Task,
    TaskComment,
    TaskCommentFile,
    TaskCommmentsGetResponse,
    TaskCommmentsPostRequestBody,
    TaskCommmentsTaskCommentIdFilesGetResponse,
    TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody,
    TaskCommmentsTaskCommentIdPutRequestBody,
    TaskStatus,
    TasksGetResponse,
    TasksPostRequestBody,
    TasksStatusPostRequestBodyItem,
    TasksTaskIdFavoriteGetResponse,
    TasksTaskIdFavoritePostRequestBody,
    TasksTaskIdPutRequestBody,
} from '../models';

export interface TaskCommmentsGetRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    id?: number;
    idGt?: number;
    idLt?: number;
    createdAt?: Date;
    createdAtGt?: Date;
    createdAtLt?: Date;
    ordering?: string;
}

export interface TaskCommmentsPostRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommmentsPostRequestBody: TaskCommmentsPostRequestBody;
}

export interface TaskCommmentsTaskCommentIdDeleteRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommentId: number;
}

export interface TaskCommmentsTaskCommentIdFilesGetRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommentId: number;
}

export interface TaskCommmentsTaskCommentIdFilesPostRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommentId: number;
    name: string;
    file: Blob;
}

export interface TaskCommmentsTaskCommentIdFilesTaskCommentFileIdDeleteRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommentId: number;
    taskCommentFileId: string;
}

export interface TaskCommmentsTaskCommentIdFilesTaskCommentFileIdGetRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommentId: number;
    taskCommentFileId: string;
}

export interface TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommentId: number;
    taskCommentFileId: string;
    taskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody: TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody;
}

export interface TaskCommmentsTaskCommentIdGetRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommentId: number;
}

export interface TaskCommmentsTaskCommentIdPutRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    taskCommentId: number;
    taskCommmentsTaskCommentIdPutRequestBody: TaskCommmentsTaskCommentIdPutRequestBody;
}

export interface TasksGetRequest {
    spaceId: number;
    projectId: number;
    page?: number;
    limit?: number;
    id?: number;
    idGt?: number;
    idLt?: number;
    subject?: string;
    status?: number;
    batonUser?: number;
    writeUser?: number;
    updatedAt?: Date;
    updatedAtGt?: Date;
    updatedAtLt?: Date;
    favorite?: boolean;
    ordering?: string;
}

export interface TasksPostRequest {
    spaceId: number;
    projectId: number;
    tasksPostRequestBody: TasksPostRequestBody;
}

export interface TasksStatusGetRequest {
    spaceId: number;
    projectId: number;
}

export interface TasksStatusPostRequest {
    spaceId: number;
    projectId: number;
    tasksStatusPostRequestBodyItem: Array<TasksStatusPostRequestBodyItem>;
}

export interface TasksTaskIdDeleteRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
}

export interface TasksTaskIdFavoriteGetRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
}

export interface TasksTaskIdFavoritePostRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    tasksTaskIdFavoritePostRequestBody: TasksTaskIdFavoritePostRequestBody;
}

export interface TasksTaskIdGetRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
}

export interface TasksTaskIdPutRequest {
    spaceId: number;
    projectId: number;
    taskId: number;
    tasksTaskIdPutRequestBody: TasksTaskIdPutRequestBody;
}

/**
 * no description
 */
export class TasksApi extends BaseAPI {

    /**
     */
    taskCommmentsGet(requestParameters: TaskCommmentsGetRequest): Observable<TaskCommmentsGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsGet.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsGet.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.id !== undefined && requestParameters.id !== null) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.idGt !== undefined && requestParameters.idGt !== null) {
            queryParameters['id__gt'] = requestParameters.idGt;
        }

        if (requestParameters.idLt !== undefined && requestParameters.idLt !== null) {
            queryParameters['id__lt'] = requestParameters.idLt;
        }

        if (requestParameters.createdAt !== undefined && requestParameters.createdAt !== null) {
            queryParameters['created_at'] = (requestParameters.createdAt as any).toISOString();
        }

        if (requestParameters.createdAtGt !== undefined && requestParameters.createdAtGt !== null) {
            queryParameters['created_at__gt'] = (requestParameters.createdAtGt as any).toISOString();
        }

        if (requestParameters.createdAtLt !== undefined && requestParameters.createdAtLt !== null) {
            queryParameters['created_at__lt'] = (requestParameters.createdAtLt as any).toISOString();
        }

        if (requestParameters.ordering !== undefined && requestParameters.ordering !== null) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TaskCommmentsGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    taskCommmentsPost(requestParameters: TaskCommmentsPostRequest): Observable<TaskComment> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsPost.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsPost.');
        }

        if (requestParameters.taskCommmentsPostRequestBody === null || requestParameters.taskCommmentsPostRequestBody === undefined) {
            throw new RequiredError('taskCommmentsPostRequestBody','Required parameter requestParameters.taskCommmentsPostRequestBody was null or undefined when calling taskCommmentsPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TaskComment>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.taskCommmentsPostRequestBody,
        });
    }

    /**
     */
    taskCommmentsTaskCommentIdDelete(requestParameters: TaskCommmentsTaskCommentIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsTaskCommentIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsTaskCommentIdDelete.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsTaskCommentIdDelete.');
        }

        if (requestParameters.taskCommentId === null || requestParameters.taskCommentId === undefined) {
            throw new RequiredError('taskCommentId','Required parameter requestParameters.taskCommentId was null or undefined when calling taskCommmentsTaskCommentIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/{taskCommentId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))).replace(`{${"taskCommentId"}}`, encodeURIComponent(String(requestParameters.taskCommentId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    taskCommmentsTaskCommentIdFilesGet(requestParameters: TaskCommmentsTaskCommentIdFilesGetRequest): Observable<TaskCommmentsTaskCommentIdFilesGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsTaskCommentIdFilesGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsTaskCommentIdFilesGet.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsTaskCommentIdFilesGet.');
        }

        if (requestParameters.taskCommentId === null || requestParameters.taskCommentId === undefined) {
            throw new RequiredError('taskCommentId','Required parameter requestParameters.taskCommentId was null or undefined when calling taskCommmentsTaskCommentIdFilesGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TaskCommmentsTaskCommentIdFilesGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/{taskCommentId}/files/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))).replace(`{${"taskCommentId"}}`, encodeURIComponent(String(requestParameters.taskCommentId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    taskCommmentsTaskCommentIdFilesPost(requestParameters: TaskCommmentsTaskCommentIdFilesPostRequest): Observable<TaskCommentFile> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsTaskCommentIdFilesPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsTaskCommentIdFilesPost.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsTaskCommentIdFilesPost.');
        }

        if (requestParameters.taskCommentId === null || requestParameters.taskCommentId === undefined) {
            throw new RequiredError('taskCommentId','Required parameter requestParameters.taskCommentId was null or undefined when calling taskCommmentsTaskCommentIdFilesPost.');
        }

        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new RequiredError('name','Required parameter requestParameters.name was null or undefined when calling taskCommmentsTaskCommentIdFilesPost.');
        }

        if (requestParameters.file === null || requestParameters.file === undefined) {
            throw new RequiredError('file','Required parameter requestParameters.file was null or undefined when calling taskCommmentsTaskCommentIdFilesPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const formData = new FormData();
        if (requestParameters.name !== undefined) {
            formData.append('name', requestParameters.name as any);
        }

        if (requestParameters.file !== undefined) {
            formData.append('file', requestParameters.file as any);
        }

        return this.request<TaskCommentFile>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/{taskCommentId}/files/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))).replace(`{${"taskCommentId"}}`, encodeURIComponent(String(requestParameters.taskCommentId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formData,
        });
    }

    /**
     */
    taskCommmentsTaskCommentIdFilesTaskCommentFileIdDelete(requestParameters: TaskCommmentsTaskCommentIdFilesTaskCommentFileIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdDelete.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdDelete.');
        }

        if (requestParameters.taskCommentId === null || requestParameters.taskCommentId === undefined) {
            throw new RequiredError('taskCommentId','Required parameter requestParameters.taskCommentId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdDelete.');
        }

        if (requestParameters.taskCommentFileId === null || requestParameters.taskCommentFileId === undefined) {
            throw new RequiredError('taskCommentFileId','Required parameter requestParameters.taskCommentFileId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/{taskCommentId}/files/{taskCommentFileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))).replace(`{${"taskCommentId"}}`, encodeURIComponent(String(requestParameters.taskCommentId))).replace(`{${"taskCommentFileId"}}`, encodeURIComponent(String(requestParameters.taskCommentFileId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    taskCommmentsTaskCommentIdFilesTaskCommentFileIdGet(requestParameters: TaskCommmentsTaskCommentIdFilesTaskCommentFileIdGetRequest): Observable<TaskCommentFile> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdGet.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdGet.');
        }

        if (requestParameters.taskCommentId === null || requestParameters.taskCommentId === undefined) {
            throw new RequiredError('taskCommentId','Required parameter requestParameters.taskCommentId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdGet.');
        }

        if (requestParameters.taskCommentFileId === null || requestParameters.taskCommentFileId === undefined) {
            throw new RequiredError('taskCommentFileId','Required parameter requestParameters.taskCommentFileId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TaskCommentFile>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/{taskCommentId}/files/{taskCommentFileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))).replace(`{${"taskCommentId"}}`, encodeURIComponent(String(requestParameters.taskCommentId))).replace(`{${"taskCommentFileId"}}`, encodeURIComponent(String(requestParameters.taskCommentFileId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    taskCommmentsTaskCommentIdFilesTaskCommentFileIdPut(requestParameters: TaskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequest): Observable<TaskCommentFile> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdPut.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdPut.');
        }

        if (requestParameters.taskCommentId === null || requestParameters.taskCommentId === undefined) {
            throw new RequiredError('taskCommentId','Required parameter requestParameters.taskCommentId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdPut.');
        }

        if (requestParameters.taskCommentFileId === null || requestParameters.taskCommentFileId === undefined) {
            throw new RequiredError('taskCommentFileId','Required parameter requestParameters.taskCommentFileId was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdPut.');
        }

        if (requestParameters.taskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody === null || requestParameters.taskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody === undefined) {
            throw new RequiredError('taskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody','Required parameter requestParameters.taskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody was null or undefined when calling taskCommmentsTaskCommentIdFilesTaskCommentFileIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TaskCommentFile>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/{taskCommentId}/files/{taskCommentFileId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))).replace(`{${"taskCommentId"}}`, encodeURIComponent(String(requestParameters.taskCommentId))).replace(`{${"taskCommentFileId"}}`, encodeURIComponent(String(requestParameters.taskCommentFileId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.taskCommmentsTaskCommentIdFilesTaskCommentFileIdPutRequestBody,
        });
    }

    /**
     */
    taskCommmentsTaskCommentIdGet(requestParameters: TaskCommmentsTaskCommentIdGetRequest): Observable<TaskComment> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsTaskCommentIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsTaskCommentIdGet.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsTaskCommentIdGet.');
        }

        if (requestParameters.taskCommentId === null || requestParameters.taskCommentId === undefined) {
            throw new RequiredError('taskCommentId','Required parameter requestParameters.taskCommentId was null or undefined when calling taskCommmentsTaskCommentIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TaskComment>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/{taskCommentId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))).replace(`{${"taskCommentId"}}`, encodeURIComponent(String(requestParameters.taskCommentId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    taskCommmentsTaskCommentIdPut(requestParameters: TaskCommmentsTaskCommentIdPutRequest): Observable<TaskComment> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling taskCommmentsTaskCommentIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling taskCommmentsTaskCommentIdPut.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling taskCommmentsTaskCommentIdPut.');
        }

        if (requestParameters.taskCommentId === null || requestParameters.taskCommentId === undefined) {
            throw new RequiredError('taskCommentId','Required parameter requestParameters.taskCommentId was null or undefined when calling taskCommmentsTaskCommentIdPut.');
        }

        if (requestParameters.taskCommmentsTaskCommentIdPutRequestBody === null || requestParameters.taskCommmentsTaskCommentIdPutRequestBody === undefined) {
            throw new RequiredError('taskCommmentsTaskCommentIdPutRequestBody','Required parameter requestParameters.taskCommmentsTaskCommentIdPutRequestBody was null or undefined when calling taskCommmentsTaskCommentIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TaskComment>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/comments/{taskCommentId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))).replace(`{${"taskCommentId"}}`, encodeURIComponent(String(requestParameters.taskCommentId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.taskCommmentsTaskCommentIdPutRequestBody,
        });
    }

    /**
     */
    tasksGet(requestParameters: TasksGetRequest): Observable<TasksGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksGet.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.page !== undefined && requestParameters.page !== null) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined && requestParameters.limit !== null) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.id !== undefined && requestParameters.id !== null) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.idGt !== undefined && requestParameters.idGt !== null) {
            queryParameters['id__gt'] = requestParameters.idGt;
        }

        if (requestParameters.idLt !== undefined && requestParameters.idLt !== null) {
            queryParameters['id__lt'] = requestParameters.idLt;
        }

        if (requestParameters.subject !== undefined && requestParameters.subject !== null) {
            queryParameters['subject'] = requestParameters.subject;
        }

        if (requestParameters.status !== undefined && requestParameters.status !== null) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.batonUser !== undefined && requestParameters.batonUser !== null) {
            queryParameters['baton_user'] = requestParameters.batonUser;
        }

        if (requestParameters.writeUser !== undefined && requestParameters.writeUser !== null) {
            queryParameters['write_user'] = requestParameters.writeUser;
        }

        if (requestParameters.updatedAt !== undefined && requestParameters.updatedAt !== null) {
            queryParameters['updated_at'] = (requestParameters.updatedAt as any).toISOString();
        }

        if (requestParameters.updatedAtGt !== undefined && requestParameters.updatedAtGt !== null) {
            queryParameters['updated_at__gt'] = (requestParameters.updatedAtGt as any).toISOString();
        }

        if (requestParameters.updatedAtLt !== undefined && requestParameters.updatedAtLt !== null) {
            queryParameters['updated_at__lt'] = (requestParameters.updatedAtLt as any).toISOString();
        }

        if (requestParameters.favorite !== undefined && requestParameters.favorite !== null) {
            queryParameters['favorite'] = requestParameters.favorite;
        }

        if (requestParameters.ordering !== undefined && requestParameters.ordering !== null) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TasksGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    tasksPost(requestParameters: TasksPostRequest): Observable<Task> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksPost.');
        }

        if (requestParameters.tasksPostRequestBody === null || requestParameters.tasksPostRequestBody === undefined) {
            throw new RequiredError('tasksPostRequestBody','Required parameter requestParameters.tasksPostRequestBody was null or undefined when calling tasksPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Task>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.tasksPostRequestBody,
        });
    }

    /**
     */
    tasksStatusGet(requestParameters: TasksStatusGetRequest): Observable<Array<TaskStatus>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksStatusGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksStatusGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Array<TaskStatus>>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/status/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    tasksStatusPost(requestParameters: TasksStatusPostRequest): Observable<TaskStatus> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksStatusPost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksStatusPost.');
        }

        if (requestParameters.tasksStatusPostRequestBodyItem === null || requestParameters.tasksStatusPostRequestBodyItem === undefined) {
            throw new RequiredError('tasksStatusPostRequestBodyItem','Required parameter requestParameters.tasksStatusPostRequestBodyItem was null or undefined when calling tasksStatusPost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TaskStatus>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/status/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.tasksStatusPostRequestBodyItem,
        });
    }

    /**
     */
    tasksTaskIdDelete(requestParameters: TasksTaskIdDeleteRequest): Observable<void> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksTaskIdDelete.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksTaskIdDelete.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling tasksTaskIdDelete.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<void>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    tasksTaskIdFavoriteGet(requestParameters: TasksTaskIdFavoriteGetRequest): Observable<TasksTaskIdFavoriteGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksTaskIdFavoriteGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksTaskIdFavoriteGet.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling tasksTaskIdFavoriteGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TasksTaskIdFavoriteGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/favorite/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    tasksTaskIdFavoritePost(requestParameters: TasksTaskIdFavoritePostRequest): Observable<TasksTaskIdFavoriteGetResponse> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksTaskIdFavoritePost.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksTaskIdFavoritePost.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling tasksTaskIdFavoritePost.');
        }

        if (requestParameters.tasksTaskIdFavoritePostRequestBody === null || requestParameters.tasksTaskIdFavoritePostRequestBody === undefined) {
            throw new RequiredError('tasksTaskIdFavoritePostRequestBody','Required parameter requestParameters.tasksTaskIdFavoritePostRequestBody was null or undefined when calling tasksTaskIdFavoritePost.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<TasksTaskIdFavoriteGetResponse>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/favorite/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.tasksTaskIdFavoritePostRequestBody,
        });
    }

    /**
     */
    tasksTaskIdGet(requestParameters: TasksTaskIdGetRequest): Observable<Task> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksTaskIdGet.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksTaskIdGet.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling tasksTaskIdGet.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Task>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     */
    tasksTaskIdPut(requestParameters: TasksTaskIdPutRequest): Observable<Task> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling tasksTaskIdPut.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling tasksTaskIdPut.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling tasksTaskIdPut.');
        }

        if (requestParameters.tasksTaskIdPutRequestBody === null || requestParameters.tasksTaskIdPutRequestBody === undefined) {
            throw new RequiredError('tasksTaskIdPutRequestBody','Required parameter requestParameters.tasksTaskIdPutRequestBody was null or undefined when calling tasksTaskIdPut.');
        }

        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        return this.request<Task>({
            path: `/spaces/{spaceId}/projects/{projectId}/tasks/{taskId}/`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.tasksTaskIdPutRequestBody,
        });
    }

}
