// tslint:disable
/**
 * pjmtool
 * pjmtool API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    MyUser,
    MyUserFromJSON,
    MyUserToJSON,
    SelectLoginUser,
    SelectLoginUserFromJSON,
    SelectLoginUserToJSON,
    UsersEmailLoginConfirmPostRequestBody,
    UsersEmailLoginConfirmPostRequestBodyFromJSON,
    UsersEmailLoginConfirmPostRequestBodyToJSON,
    UsersEmailLoginPostRequestBody,
    UsersEmailLoginPostRequestBodyFromJSON,
    UsersEmailLoginPostRequestBodyToJSON,
    UsersLoginPostRequestBody,
    UsersLoginPostRequestBodyFromJSON,
    UsersLoginPostRequestBodyToJSON,
    UsersLoginPostResponse,
    UsersLoginPostResponseFromJSON,
    UsersLoginPostResponseToJSON,
    UsersMeEmailConfirmPostRequestBody,
    UsersMeEmailConfirmPostRequestBodyFromJSON,
    UsersMeEmailConfirmPostRequestBodyToJSON,
    UsersMeEmailGetResponse,
    UsersMeEmailGetResponseFromJSON,
    UsersMeEmailGetResponseToJSON,
    UsersMeEmailPutRequestBody,
    UsersMeEmailPutRequestBodyFromJSON,
    UsersMeEmailPutRequestBodyToJSON,
    UsersMePutRequestBody,
    UsersMePutRequestBodyFromJSON,
    UsersMePutRequestBodyToJSON,
    UsersMeSmsConfirmPostRequestBody,
    UsersMeSmsConfirmPostRequestBodyFromJSON,
    UsersMeSmsConfirmPostRequestBodyToJSON,
    UsersMeSmsGetResponse,
    UsersMeSmsGetResponseFromJSON,
    UsersMeSmsGetResponseToJSON,
    UsersMeSmsPutRequestBody,
    UsersMeSmsPutRequestBodyFromJSON,
    UsersMeSmsPutRequestBodyToJSON,
    UsersSmsLoginConfirmPostRequestBody,
    UsersSmsLoginConfirmPostRequestBodyFromJSON,
    UsersSmsLoginConfirmPostRequestBodyToJSON,
    UsersSmsLoginConfirmPostResponse,
    UsersSmsLoginConfirmPostResponseFromJSON,
    UsersSmsLoginConfirmPostResponseToJSON,
    UsersSmsLoginPostRequestBody,
    UsersSmsLoginPostRequestBodyFromJSON,
    UsersSmsLoginPostRequestBodyToJSON,
} from '../models';

export interface UsersEmailLoginConfirmPostRequest {
    usersEmailLoginConfirmPostRequestBody: UsersEmailLoginConfirmPostRequestBody;
}

export interface UsersEmailLoginPostRequest {
    usersEmailLoginPostRequestBody: UsersEmailLoginPostRequestBody;
}

export interface UsersLoginPostRequest {
    usersLoginPostRequestBody: UsersLoginPostRequestBody;
}

export interface UsersMeEmailConfirmPostRequest {
    usersMeEmailConfirmPostRequestBody: UsersMeEmailConfirmPostRequestBody;
}

export interface UsersMeEmailPutRequest {
    usersMeEmailPutRequestBody: UsersMeEmailPutRequestBody;
}

export interface UsersMePutRequest {
    usersMePutRequestBody: UsersMePutRequestBody;
}

export interface UsersMeSmsConfirmPostRequest {
    usersMeSmsConfirmPostRequestBody: UsersMeSmsConfirmPostRequestBody;
}

export interface UsersMeSmsPutRequest {
    usersMeSmsPutRequestBody: UsersMeSmsPutRequestBody;
}

export interface UsersSmsLoginConfirmPostRequest {
    usersSmsLoginConfirmPostRequestBody: UsersSmsLoginConfirmPostRequestBody;
}

export interface UsersSmsLoginPostRequest {
    usersSmsLoginPostRequestBody: UsersSmsLoginPostRequestBody;
}

/**
 * no description
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * ログイン用メール認証メッセージ送信
     */
    async usersEmailLoginConfirmPostRaw(requestParameters: UsersEmailLoginConfirmPostRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.usersEmailLoginConfirmPostRequestBody === null || requestParameters.usersEmailLoginConfirmPostRequestBody === undefined) {
            throw new runtime.RequiredError('usersEmailLoginConfirmPostRequestBody','Required parameter requestParameters.usersEmailLoginConfirmPostRequestBody was null or undefined when calling usersEmailLoginConfirmPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/email_login/confirm/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersEmailLoginConfirmPostRequestBodyToJSON(requestParameters.usersEmailLoginConfirmPostRequestBody),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ログイン用メール認証メッセージ送信
     */
    async usersEmailLoginConfirmPost(requestParameters: UsersEmailLoginConfirmPostRequest): Promise<void> {
        await this.usersEmailLoginConfirmPostRaw(requestParameters);
    }

    /**
     * メール認証通過後、ログイン可能なユーザーの一覧を取得
     */
    async usersEmailLoginPostRaw(requestParameters: UsersEmailLoginPostRequest): Promise<runtime.ApiResponse<Array<SelectLoginUser>>> {
        if (requestParameters.usersEmailLoginPostRequestBody === null || requestParameters.usersEmailLoginPostRequestBody === undefined) {
            throw new runtime.RequiredError('usersEmailLoginPostRequestBody','Required parameter requestParameters.usersEmailLoginPostRequestBody was null or undefined when calling usersEmailLoginPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/email_login/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersEmailLoginPostRequestBodyToJSON(requestParameters.usersEmailLoginPostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SelectLoginUserFromJSON));
    }

    /**
     * メール認証通過後、ログイン可能なユーザーの一覧を取得
     */
    async usersEmailLoginPost(requestParameters: UsersEmailLoginPostRequest): Promise<Array<SelectLoginUser>> {
        const response = await this.usersEmailLoginPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * メール or SMS認証で得たログイン用トークンを使ってログイン
     */
    async usersLoginPostRaw(requestParameters: UsersLoginPostRequest): Promise<runtime.ApiResponse<UsersLoginPostResponse>> {
        if (requestParameters.usersLoginPostRequestBody === null || requestParameters.usersLoginPostRequestBody === undefined) {
            throw new runtime.RequiredError('usersLoginPostRequestBody','Required parameter requestParameters.usersLoginPostRequestBody was null or undefined when calling usersLoginPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/login/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersLoginPostRequestBodyToJSON(requestParameters.usersLoginPostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersLoginPostResponseFromJSON(jsonValue));
    }

    /**
     * メール or SMS認証で得たログイン用トークンを使ってログイン
     */
    async usersLoginPost(requestParameters: UsersLoginPostRequest): Promise<UsersLoginPostResponse> {
        const response = await this.usersLoginPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * メール変更用メール認証メッセージ送信
     */
    async usersMeEmailConfirmPostRaw(requestParameters: UsersMeEmailConfirmPostRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.usersMeEmailConfirmPostRequestBody === null || requestParameters.usersMeEmailConfirmPostRequestBody === undefined) {
            throw new runtime.RequiredError('usersMeEmailConfirmPostRequestBody','Required parameter requestParameters.usersMeEmailConfirmPostRequestBody was null or undefined when calling usersMeEmailConfirmPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/users/me/email/confirm/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersMeEmailConfirmPostRequestBodyToJSON(requestParameters.usersMeEmailConfirmPostRequestBody),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * メール変更用メール認証メッセージ送信
     */
    async usersMeEmailConfirmPost(requestParameters: UsersMeEmailConfirmPostRequest): Promise<void> {
        await this.usersMeEmailConfirmPostRaw(requestParameters);
    }

    /**
     * 自身のメール取得
     */
    async usersMeEmailGetRaw(): Promise<runtime.ApiResponse<UsersMeEmailGetResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/users/me/email/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersMeEmailGetResponseFromJSON(jsonValue));
    }

    /**
     * 自身のメール取得
     */
    async usersMeEmailGet(): Promise<UsersMeEmailGetResponse> {
        const response = await this.usersMeEmailGetRaw();
        return await response.value();
    }

    /**
     * メール認証通過後、メール変更
     */
    async usersMeEmailPutRaw(requestParameters: UsersMeEmailPutRequest): Promise<runtime.ApiResponse<UsersMeEmailGetResponse>> {
        if (requestParameters.usersMeEmailPutRequestBody === null || requestParameters.usersMeEmailPutRequestBody === undefined) {
            throw new runtime.RequiredError('usersMeEmailPutRequestBody','Required parameter requestParameters.usersMeEmailPutRequestBody was null or undefined when calling usersMeEmailPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/users/me/email/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UsersMeEmailPutRequestBodyToJSON(requestParameters.usersMeEmailPutRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersMeEmailGetResponseFromJSON(jsonValue));
    }

    /**
     * メール認証通過後、メール変更
     */
    async usersMeEmailPut(requestParameters: UsersMeEmailPutRequest): Promise<UsersMeEmailGetResponse> {
        const response = await this.usersMeEmailPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * 自身のユーザー情報を取得
     */
    async usersMeGetRaw(): Promise<runtime.ApiResponse<MyUser>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/users/me/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => MyUserFromJSON(jsonValue));
    }

    /**
     * 自身のユーザー情報を取得
     */
    async usersMeGet(): Promise<MyUser> {
        const response = await this.usersMeGetRaw();
        return await response.value();
    }

    /**
     * 自身のユーザー情報を更新
     */
    async usersMePutRaw(requestParameters: UsersMePutRequest): Promise<runtime.ApiResponse<MyUser>> {
        if (requestParameters.usersMePutRequestBody === null || requestParameters.usersMePutRequestBody === undefined) {
            throw new runtime.RequiredError('usersMePutRequestBody','Required parameter requestParameters.usersMePutRequestBody was null or undefined when calling usersMePut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/users/me/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UsersMePutRequestBodyToJSON(requestParameters.usersMePutRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => MyUserFromJSON(jsonValue));
    }

    /**
     * 自身のユーザー情報を更新
     */
    async usersMePut(requestParameters: UsersMePutRequest): Promise<MyUser> {
        const response = await this.usersMePutRaw(requestParameters);
        return await response.value();
    }

    /**
     * SMS変更用SMS認証メッセージ送信
     */
    async usersMeSmsConfirmPostRaw(requestParameters: UsersMeSmsConfirmPostRequest): Promise<runtime.ApiResponse<UsersSmsLoginConfirmPostResponse>> {
        if (requestParameters.usersMeSmsConfirmPostRequestBody === null || requestParameters.usersMeSmsConfirmPostRequestBody === undefined) {
            throw new runtime.RequiredError('usersMeSmsConfirmPostRequestBody','Required parameter requestParameters.usersMeSmsConfirmPostRequestBody was null or undefined when calling usersMeSmsConfirmPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/users/me/sms/confirm/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersMeSmsConfirmPostRequestBodyToJSON(requestParameters.usersMeSmsConfirmPostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersSmsLoginConfirmPostResponseFromJSON(jsonValue));
    }

    /**
     * SMS変更用SMS認証メッセージ送信
     */
    async usersMeSmsConfirmPost(requestParameters: UsersMeSmsConfirmPostRequest): Promise<UsersSmsLoginConfirmPostResponse> {
        const response = await this.usersMeSmsConfirmPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * 自身のSMS取得
     */
    async usersMeSmsGetRaw(): Promise<runtime.ApiResponse<UsersMeSmsGetResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/users/me/sms/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersMeSmsGetResponseFromJSON(jsonValue));
    }

    /**
     * 自身のSMS取得
     */
    async usersMeSmsGet(): Promise<UsersMeSmsGetResponse> {
        const response = await this.usersMeSmsGetRaw();
        return await response.value();
    }

    /**
     * SMS認証通過後、SMS変更
     */
    async usersMeSmsPutRaw(requestParameters: UsersMeSmsPutRequest): Promise<runtime.ApiResponse<UsersMeSmsGetResponse>> {
        if (requestParameters.usersMeSmsPutRequestBody === null || requestParameters.usersMeSmsPutRequestBody === undefined) {
            throw new runtime.RequiredError('usersMeSmsPutRequestBody','Required parameter requestParameters.usersMeSmsPutRequestBody was null or undefined when calling usersMeSmsPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // token authentication
        }

        const response = await this.request({
            path: `/users/me/sms/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UsersMeSmsPutRequestBodyToJSON(requestParameters.usersMeSmsPutRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersMeSmsGetResponseFromJSON(jsonValue));
    }

    /**
     * SMS認証通過後、SMS変更
     */
    async usersMeSmsPut(requestParameters: UsersMeSmsPutRequest): Promise<UsersMeSmsGetResponse> {
        const response = await this.usersMeSmsPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * ログイン用SMS認証メッセージ送信
     */
    async usersSmsLoginConfirmPostRaw(requestParameters: UsersSmsLoginConfirmPostRequest): Promise<runtime.ApiResponse<UsersSmsLoginConfirmPostResponse>> {
        if (requestParameters.usersSmsLoginConfirmPostRequestBody === null || requestParameters.usersSmsLoginConfirmPostRequestBody === undefined) {
            throw new runtime.RequiredError('usersSmsLoginConfirmPostRequestBody','Required parameter requestParameters.usersSmsLoginConfirmPostRequestBody was null or undefined when calling usersSmsLoginConfirmPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/sms_login/confirm/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersSmsLoginConfirmPostRequestBodyToJSON(requestParameters.usersSmsLoginConfirmPostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersSmsLoginConfirmPostResponseFromJSON(jsonValue));
    }

    /**
     * ログイン用SMS認証メッセージ送信
     */
    async usersSmsLoginConfirmPost(requestParameters: UsersSmsLoginConfirmPostRequest): Promise<UsersSmsLoginConfirmPostResponse> {
        const response = await this.usersSmsLoginConfirmPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * SMS認証通過後、ログイン可能なユーザーの一覧を取得
     */
    async usersSmsLoginPostRaw(requestParameters: UsersSmsLoginPostRequest): Promise<runtime.ApiResponse<Array<SelectLoginUser>>> {
        if (requestParameters.usersSmsLoginPostRequestBody === null || requestParameters.usersSmsLoginPostRequestBody === undefined) {
            throw new runtime.RequiredError('usersSmsLoginPostRequestBody','Required parameter requestParameters.usersSmsLoginPostRequestBody was null or undefined when calling usersSmsLoginPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/sms_login/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersSmsLoginPostRequestBodyToJSON(requestParameters.usersSmsLoginPostRequestBody),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SelectLoginUserFromJSON));
    }

    /**
     * SMS認証通過後、ログイン可能なユーザーの一覧を取得
     */
    async usersSmsLoginPost(requestParameters: UsersSmsLoginPostRequest): Promise<Array<SelectLoginUser>> {
        const response = await this.usersSmsLoginPostRaw(requestParameters);
        return await response.value();
    }

}
